// Generated by CoffeeScript 2.5.1
(function() {
  var dictionary, filterEntry, getRandomEntry, onclickRandomState, pickQuestionAndAnswer, search, selectable, setSearchResults, setSearchValue,
    indexOf = [].indexOf;

  getRandomEntry = function() {
    return dictionary[Math.floor(Math.random() * dictionary.length)];
  };

  filterEntry = function(exp, prefix = '') {
    var re;
    try {
      re = new RegExp(`${prefix}${exp.trim()}`);
    } catch (error) {
      return function() {
        return false;
      };
    }
    return function(entry) {
      return re.test(entry.tokipona) || re.test(entry.english);
    };
  };

  search = function(exp) {
    var exactMatches, otherMatches;
    if (!exp) {
      return [];
    }
    exactMatches = dictionary.filter(filterEntry(exp, '^'));
    otherMatches = dictionary.filter(function(e) {
      return indexOf.call(exactMatches, e) < 0;
    }).filter(filterEntry(exp));
    return exactMatches.concat(otherMatches).slice(0, 100);
  };

  setSearchResults = function() {
    var results;
    results = search(document.getElementById('search').value);
    return document.getElementById('results').innerHTML = results.map(function(e) {
      return `${e.tokiponaHTML} :: ${e.englishHTML}`;
    }).join('<br />');
  };

  setSearchValue = function(text) {
    document.getElementById('search').value = text;
    return setSearchResults();
  };

  selectable = function(text) {
    return text.replace(/[A-Za-z]+/g, function(word) {
      return `<a onclick='tokipona.setSearchValue("${word}")'>${word}</a>`;
    });
  };

  
  onclickRandomState = null;

  pickQuestionAndAnswer = function() {
    var a, entry, q;
    if (!onclickRandomState) {
      entry = getRandomEntry();
      [q, a] = Math.random() > .5 ? ['tokipona', 'english'] : ['english', 'tokipona'];
      onclickRandomState = {
        question: entry[q + 'HTML'],
        answer: entry[a + 'HTML']
      };
      document.getElementById('question').innerHTML = onclickRandomState.question;
      return document.getElementById('answer').innerHTML = '?';
    } else {
      document.getElementById('answer').innerHTML = onclickRandomState.answer;
      return onclickRandomState = null;
    }
  };

  
  window.tokipona = {pickQuestionAndAnswer, setSearchResults, setSearchValue};

  
  dictionary = `a a a! :: Ha ha ha! (Gelächter, Lachen) 
a a a! :: Hahaha! (Lachen) 
a a a! :: Interjektion: Lachen 
a a a! ni li ' musi. :: Hahaha! Das ist lustig. 
a! akesi li wile moku e mi! :: Oh! Der Dinosaurier will mich fressen. 
A: a! sina lukin ala lukin e ijo nasa ni? :: A: Wow! Hast du dieses seltsame Ding gesehen? 
a :: Interjektion: ah, ha, uh, oh, ooh, aw, well (emotionales Wort) 
Akanisan :: Afghanistan 
akesi :: Adjektiv: Amphibien-, Reptilien-, schleimig 
akesi :: Gecko, Echse, Schlange, Dinosaurier, Schildkröte. 
akesi li pakala moli e soweli. :: Der Waran attackierte die Ziege tödlich. 
akesi li pana e telo moli. :: Die Schlange gab Gift. 
akesi pi telo moli :: Giftiges Reptil, Giftschlange, giftiger Frosch 
akesi :: Substantiv: Reptil, Lurch, Amphibie, Saurier, Schlange, Drache, Frosch, Schildkröte 
ala :: 0 
ala :: Adjektiv: nein, nichts, un- 
ala :: Adjektiv, Ziffer: Null, 0 
ala :: Adverb: nicht, un- 
ala! :: Interjektion: Nein! 
ala li ' jaki. :: Nichts ist dreckig. 
Alan :: Irland, Gälisch 
alasa :: Adjektiv: jagend 
alasa (e ) :: Verb, transitiv: jagen, verfolgen und töten, nach Futter suchen 
alasa li pana e soweli, tawa mi. :: Die Jagd bringt mir Fleisch. 
alasa :: Substantiv: Jagd 
ala :: Substantiv: Nichts, Negation, Null 
ale :: Adjektiv: alle(r/s), je, jeweils, komplett, ganz, (ale = ali), (veraltet) 
ale :: Adjektiv, Ziffer: 100 (offizielles Toki Pona Buch) 
ale :: Adverb: alle(r/s), je, jeweils, komplett, ganz, (ale = ali), (veraltet) 
ale li jo e tenpo. :: Alles hat seine Zeit. 
ale li pona :: Alles ist gut. 
ale li ' pona. :: Alles wird gut. 
Alensina :: Argentinien 
ale :: Substantiv: Alles, Etwas, Leben, Universium, Welt (veraltet) 
ale tu :: 100 + 2 = 102 (Wird selten verwendet.) 
ali :: Adjektiv: alle(r/s), je, jeweils, komplett, ganz 
ali :: Adverb: alle(r/s), je, jeweils, komplett, ganz 
ali li ' pona, tawa mi. :: Für mich ist alles in Ordnung. 
ali li ' seme? :: Die Frage nach dem Leben, dem Universum und dem ganzen Rest. 
ali :: Substantiv: Alles, Etwas, Leben, Universium, Welt 
A: mi mute o tawa. :: A: Laß uns gehen. 
A: mi tawa, tawa ma Elopa. :: A: Ich gehe nach Europa. 
A: mi wile moku. :: Ich möchte essen. 
Anku :: Korea, Koreanisch 
anpa :: Adjektiv: unten, tief, niedrig 
anpa :: Adverb: tief, niedrig 
anpa (e ) :: Verb, transitiv: niederlassen, absenken, abseilen, herunterholen, besiegen, bezwingen 
anpa lawa :: Hals 
anpa lawa :: Hals, Rachen, Kehle, Gurgel 
anpa pi sinpin lawa :: Kinn 
anpa :: Substantiv: Boden, Erdboden, Grund, Talsohle 
anpa :: Verb, intransitiv: sich unterwerfen 
ante :: Adjektiv: unterschiedlich, verschieden (von) 
ante (e ) :: Verb, transitiv: wechseln; umschalten, ändern, abändern, verändern, modifizieren 
ante la ni li ' ike. :: Bei Abweichungen ist es ungünstig. 
ante la :: Substantiv: Wenn Unterschied, bei Abweichung, bei Differenz 
ante li kama. :: Die Zeiten ändern sich. 
ante :: Substantiv: Unterschied, Abweichung, Differenz 
Antola :: Andorra 
anu :: Konjunktion: oder 
a! :: Ohhh! 
a! telo sijelo loje li kama tan nena kute mi! :: Ahh! Blut läuft aus meinem Ohr! 
awen :: Adjektiv: bleibend; verbleibend, feststehend, ortsfest, parkend, permanent, sesshaft 
awen :: Adverb: verbleibend, noch, gerade beim ... 
awen (e ) :: Verb, transitiv: behalten; nicht weggeben 
awen pona :: geduldig 
awen pona mi li pini! :: Meine Geduld ist zu Ende! 
awen :: Substantiv: Trägheit, Kontinuität, Kontinuum, Aufenthalt 
awen :: Verb, intransitiv: bleiben, verbleiben, sich aufhalten, warten 
Awisi :: Haiti, haitisches Kreolisch 
B: en mi wile moku kin. :: Und ich möchte auch essen. 
B: mi ken ala. mi moku kin e moku. :: B: Ich kann nicht! Ich esse noch das Essen. 
B: mi lukin kin e ona. :: B: Ja, ich habe es wirklich gesehen. 
B: mi tawa kin e mi, tawa ma Elopa. :: B: Ich bewege mich auch nach Europa. 
Der Kerl verbessert nutzbringend das Werkzeug. :: jan li pona ilo e ilo. 
Der Müll beschmutzt mich ein wenig. :: jaki li jaki lili e mi. 
Die Leute möchten Land besitzen. :: jan li wile jo e ma. 
Die Maschine hebt das Dach hoch. :: ilo li sewi e sewi. 
 :: Dieser See ist kalt. 
 :: Dies ist meins. 
Die Sonne bestrahlt warm das Land. :: suno li suno seli e ma. 
Du betrachtest mich sehr sexy. :: sina lukin unpa mute e mi. 
Du kleidest dich ekelhaft albern. :: sina len nasa jaki e sina. 
Ekato :: Ecuador 
Elena :: Griechenland, Griechisch 
e mi :: Reflexivpronomen: mich, uns 
en :: Konjunktion: und (um Haupt-Substantive zu verbinden) 
e ona :: Reflexivpronomen: seins, ihres, seine, deren 
Epanja :: Spanien, Spanisch 
Er führt kämpfend die Schlacht. :: ona li lawa utala e utala. 
Er will das Werkzeug zerstören. :: ona li wile pakala e ilo. 
 :: Er wäscht sich. 
e :: Separator: Ein e leitet das direkte Objekt ein. Verwende ein e nicht zusammmen mit einem der anderen Separatoren. 
Esi :: Estland, Estnisch 
e sina :: Reflexivpronomen: dich, euch 
Esuka :: Baskenland, Baskisch 
esun :: Adjektiv: kommerziell, gewerblich, kaufmännisch, verkäuflich 
esun (e ) :: Verb, transitiv: kaufen, verkaufen, tauschen 
esun :: Substantiv: Markt, Shop 
Ich möchte Sex mit ihr haben. :: mi wile unpa e ona. 
Ich will viel Sex mit dir haben. :: mi wile unpa mute e sina. 
ijo :: Adjektiv: für etwas 
ijo :: Adverb: für etwas 
ijo (e ) :: Verb, transitiv: objektivieren 
ijo ike li lon monsi mi. :: Böse Dinge liegen hinter mir. 
ijo li lon oko mi. :: Etwas ist in meinem Auge. 
ijo li lukin e mi. :: Etwas schaut mich an. 
ijo lon tomo :: Haushaltsgegenstände 
ijo :: Substantiv: Ding, Sache, Zeug, Krempel, Gegenstand, Objekt 
ijo uta walo :: Zähne 
ike :: Adjektiv: schlecht, schlimm, übel, böse, ungezogen, falsch, zu komplex, ungesund 
ike :: Adverb: schlecht, schlimm, übel, böse, ungezogen, falsch, zu komplex, ungesund 
ike (e ) :: Verb, transitiv: schlecht machen, verschlechtern, schlechten Einfluss auf 
ike! :: Interjektion: Mist! Leider! Sch ! 
ike la sina moku e ni. :: Bei Übelkeit schlucke dies. 
ike la :: Substantiv: wenn Übel ..., bei Verderbtheit, aus Boshaftigkeit 
ike li kama. :: Böses naht. 
ike lukin :: hässlich 
ike! :: Oh nein! Mist! 
ike :: Schlechtes 
ike :: Substantiv: Negativität, Übel, Böse, Schlechtigkeit, Verderbtheit 
ike :: Verb, intransitiv: schlecht sein, jdm. in den Arsch kriechen 
Ilakija :: Irak 
Ilan :: Iran, Persisch 
ilo :: Adjektiv: nützlich 
ilo :: Adverb: nutzbringend 
ilo lape :: Schlaftabletten 
ilo li lon poki. :: Die Werkzeuge sind im Container. 
ilo li ' pakala. :: Das Werkzeug ist kaputt. 
 :: ilo li sewi e sewi. 
ilo moku :: Besteck, Gabel, Löffel, Messer, Teelöffel, Eßstäbchen 
ilo moku :: Besteck, Löffel, Gabel, Messer 
ilo musi :: Spielzeug, (Brett-) Spiel 
ilo nasa :: Drogen 
ilo nasa wawa :: Energie-Droge, z.B. Amphetamine 
ilo ni li ' lete, tawa mi. :: Die Axt fühlt sich sehr kalt an. 
ilo pi sitelen tawa :: Fernseher 
ilo pi sitelen toki :: (Schreib-) Stift, Bleistift, Kugelschreiber, Füller, 
ilo sona :: Computer, PDA 
ilo :: Substantiv: Werkzeug, Gerät, Tool, Vorrichtung, Apparat, Maschine 
ilo suno :: Lampe, Leuchte 
ilo suno :: Lampe, Taschenlampe, Scheinwerfer 
ilo toki :: Telefon, Handy, Chatroom 
ilo unpa :: Sex-Spielzeug 
Inli :: England, Englisch 
' :: inoffiziell: Ein Apostroph kann ein Prädikat, das kein Verb enthält, kennzeichnen. 
# :: inoffiziell: Zur Kennzeichnung von Zahlen 
insa :: Adjektiv: intern, zentral 
insa :: Substantiv: Innere, Innenseite, Zentrum, Magen 
Intonesija :: Indonesien, Indonesisch 
Isale :: Israel 
Isilan :: Island, Isländisch 
 :: Ist dies ein Säugetier? 
Italija :: Italien, Italienisch 
jaki :: Adjektiv: schmutzig, dreckig, schmierig, unsauber, schmuddelig, obszön 
jaki :: Adverb: schmutzig, dreckig, schmierig; unsauber; schmuddelig; versifft, grob 
jaki (e ) :: Verb, transitiv: verschmutzen, verunreinigen, verpesten 
jaki! :: Interjektion: Igit! Ekelhaft! 
 :: jaki li jaki lili e mi. 
jaki :: Substantiv: Dreck, Schmutz, Verschmutzung, Müll, Schrott, Kot 
Jamanija :: Jemen 
jan :: Adjektiv: persönlich, human, jemandes 
jan :: Adverb: persönlich, human, jemandes 
jan ala li toki. :: Niemand redet. 
jan alasa pona li ' wawa. :: Ein guter Jäger ist stark. 
jan Ana o pana e moku, tawa mi! :: Ana, gib mir Essen! 
jan Eliku Kulaputon :: Eric Clapton 
jan Elu :: Elfe 
jan Epi o a! :: Oh Abbie! 
jan Eta li ' jan unpa. :: Heather ist eine Schlampe. 
jan (e ) :: Verb, transitiv: personifizieren, verkörpern, vermenschlichen, personalisieren 
jan ike :: Feind 
jan ike li kama la o seli e lipu ni. :: Wenn der Feind kommt, verbrenne diese Papiere. 
jan ike li utala e ona mute. :: Ein Feind greift sie an. 
jan ike ni li jo e len nasa. :: Diese schlechte Person hat eigenartige Kleidung. 
jan ike :: schlechter Mensch, Trottel, Feind 
jan Jon Kalapin :: John Calvin 
jan Kanata :: Kanadier 
jan Keli o, sina ' pona lukin. :: Kelly, du bist hübsch. 
jan Ken o, mi olin e sina. :: Ken, ich liebe dich. 
jan Ken o, pipi li lon len sina. :: Ken, ein Käfer ist auf deinem T-Shirt. 
jan Kitopokolonpo :: Christopher Columbus 
jan kulupu :: Mitglied einer Gruppe 
jan laso jelo lili li kama, tan sewi. :: Kleine grüne Menschen kamen vom Himmel. 
jan laso lili :: Little Boy Blue 
jan lawa :: Anführer, Leiter, Boss, Chef 
jan lawa :: Boss, Meister, Chef, Vorsitzender, Präsident, Direktor 
jan lawa lete :: Väterchen Frost 
jan lawa li moku e telo jaki. :: Der Chef trank dreckiges Wasser. 
jan lawa ma :: Präsident eines Landes, Gouverneur, Statthalter 
jan lawa pi jan utala :: Offizier, General 
jan lawa pi ma tomo :: Bürgermeister 
jan lawa pi tomo tawa kon :: Pilot (Führer eines Flugzeuges) 
jan lawa pi tomo tawa telo li moku. :: Der Kapitän des Schiffes ißt. 
jan :: Leute 
jan li alasa e soweli. :: Jemand jagt einen Büffel. 
jan lili en jan suli li toki. :: Das Kind und der Erwachsene reden. 
jan lili :: Kind 
jan lili :: Kind, Tochter, Sohn 
jan lili :: kleine, dünne oder junge Person, Kind, Liliputaner 
jan lili li ken ala moku e telo nasa. :: Kindern dürfen kein Bier trinken. 
jan lili li lukin e jan suli. :: Die Kinder beobachten die Erwachsenen. 
jan lili li sona ala e ike. :: Kinder sind unschuldig. 
jan lili li wile e telo kili. :: Die Kinder wollen Fruchtsaft. 
jan lili pi jan Keli li ' musi. :: Kelis Kind ist lustig. 
jan lili pi jan Ken en jan Lisa li ' suwi. :: Ken und Lisas Baby ist niedlich. 
jan lili sina li ' suwi. :: Dein Baby ist süß. 
jan lili # tu wan :: drei Kinder 
jan li lon insa tomo. :: Jemand ist im Haus. 
jan li lukin e ijo ni. :: Der Kerl betrachtet dieses Ding. 
jan li lukin e ni. :: Der Kerl betrachtet jenes. 
jan li lukin, sama pipi. :: Leute sehen wie Ameisen aus. 
jan li moku. :: Jemand isst. 
jan li moli ala moli e waso? :: Hat der Mann den Vogel getötet? 
jan li moli e waso. :: Der Mann tötete den Vogel. 
jan li ' pona. :: Der Mensch ist gut. 
 :: jan li pona ilo e ilo. 
jan li ' pona. :: Menschen sind gut. 
jan li ' pona mute. :: Der Mensch ist sehr gut. / Der Mensch ist das viele Gute. 
jan Lisa li ' pona. :: Lisa ist nett. 
jan Lisa o, toki! :: Hallo Lisa! 
jan Lisa taso li kama. :: Nur Lisa kam. 
jan li seme :: Persönliche Charakterzüge, Eigenschaften 
jan li ' suli mute. mani li ' suli lili. :: Menschen sind wichtiger als Geld. 
jan li telo e ona. :: Ein Mensch wäscht sich. 
jan li toki, kepeken toki pona, lon tomo toki. :: Leute sprechen toki pona in dem Chat-Room. 
jan Lope li awen. :: Robert wartet. 
jan # luka tu :: sieben Leute 
jan Mawen o, sina wile ala wile moku? :: Marwin, hast du Hunger? 
jan Mawi li pana e seli tawa ma. :: Wie Maui das Feuer in die Welt brachte. 
jan Mesiko :: Mexikaner 
jan Mewi li toki, tawa mi. :: Mary redet mit mir. 
jan Mose o lawa e mi mute, tawa ma pona! :: Moses führe uns in das gelobte Land! 
jan mute kin li kama! :: Sehr, sehr viel Leute kamen. 
jan mute li kama. :: Viele Leute kamen. 
jan mute li kama. :: Viele Leute kommen. 
jan mute lili li kama. :: Einige Leute kommen. 
jan mute lili li kama. :: Einige Leuten kamen. 
jan nanpa tu tu :: die vierte Person 
jan nasa :: Narr, Idiot, verrückte Person, Betrunkener
jan nasa pi ilo moli li ken pana e ike. :: Waffennarren können Schlechtes bringen. 
jan nasa utala :: kämpfender Idiot 
jan Nesan li ' musi. :: Nathan ist lustig.
jan ni li kon ike. :: Dieser Mensch atmet schlecht. 
jan ni li pona. :: Dieser Typ ist gut. 
jan ni li pona lukin. :: Diese Person sieht gut aus. 
jan ni li ' sama mi. :: Diese Person ist mir ähnlich. 
jan olin :: (Lebens-) Partner 
jan olin :: (Lebens-) Partner, Geliebte, Geliebter, Schatz 
jan pakala :: eine verletzte Person, Opfer 
jan pali :: Arbeiter, Angestellter, Arbeitnehmer, Beschäftigter, Mitarbeiter 
jan pali pi ma ali o wan e ona.! :: Proletarier aller Länder, vereinigt euch! 
jan Pawe o, mi wile ala moli. :: Paul, ich möchte nicht sterben. 
jan Pentan li pana e sona, tawa mi. :: Brandon unterrichtet mich. 
jan :: Person, Mensch, Leute, Einwohner, Bewohner, Mitglied 
jan pi ike lukin :: häßliche Person 
jan pi kama sona :: Student 
jan pi ma ante :: Ausländer 
jan pi ma sama :: Mitbürger des gleichen Landes 
jan pi ma tomo :: Städter, Stadtbewohner 
jan pi musi sijelo :: Athlet, Sportler, Tänzer, Tänzerin 
jan pi nanpa wan li lon. :: Der Erste ist da. 
jan pi nasin sewi Kolisu :: Christ 
jan pi pali moku :: Koch 
jan pi pali unpa :: Prostituierte, Hure, Gigolo 
jan pi pana sona :: Lehrer, Dozent 
jan pi pona lukin :: attraktive Person 
jan pi pona pilin :: Psychologe 
jan pi pona sijelo :: Doktor, Arzt, Heilpraktiker, Mediziner 
jan pi sona nanpa :: Mathematiker 
jan pi tomo pali :: Büroangestellter 
jan pi tomo sama :: Mitbewohner, Stubenkamerad 
jan pi wawa ala :: eine Person mit Schwäche, eine schwache Person 
jan poka :: Nachbar 
jan pona :: guter Mensch, Freund 
jan pona :: guter Mensch, Freund, Kumpel, Kamerad 
jan pona mi kin li lon ni. :: Mein guter Freund ist hier. 
jan pona mi li lon poka mi. :: Mein Freund ist an meiner Seite. 
jan sama :: Geschwister, Bruder, Schwester 
jan sama :: Gleichrangiger, Bruder, Schwester, Geschwister 
jan San o tawa tomo sina! :: John, gehe nach hause! 
jan Santa :: Santa Claus 
jan seme li lon? / jan seme li lon ni? :: Wer ist da? 
jan seme li ' meli sina? :: Wer ist deine Freundin/Frau? 
jan seme li moku? :: Wer ißt? 
jan seme li olin e sina? :: Wer liebt dich? 
jan seme li tawa, lon poka sina? :: Wer ging mit dir? 
jan seme pi kulupu ni li suli? :: Welche Leute dieser Gruppe sind wichtig? 
jan Sesi o moku e kili ni! :: Jessie, esse diese Frucht! 
jan Sesi o moku e kili ni! :: Jessie, iss diese Frucht! 
jan sewi :: Heiliger, Gott, fliegendes Spaghettimonster 
jan sin li kama ala kama? :: Kommen noch mehr Leute? 
jan sin li kama. :: Es kommen noch mehr Leute. 
jan Sipi Wanta :: Stevie Wonder 
jan sona :: gebildete Person, Weiser, Akademiker, Spezialist 
jan sona li ' jan nasa. :: Ein Genie ist ungewöhnlich. 
jan sona sijelo :: Doktor, Arzt, Mediziner 
jan :: Substantiv: Mensch, Person, Leute, Jemand 
jan suli :: Erwachsener 
jan suli :: große oder dicke Person, Erwachsener 
jan Susan anu jan Lisa li moku e suwi? :: Hat Susan die Kekse gegessen oder war es Lisa? 
jan Susan li ' nasa. :: Susan ist verrückt. 
jan Ta o toki ala, tawa mi! :: Todd, sprich nicht zu mir! 
jan Tepani o, sina ' ike, tawa mi. :: Stefanie, ich mag dich nicht. 
jan toki :: Sprecher, Bote, Kurier 
jan Toni Kena :: Tony Chestnut 
jan unpa :: Liebhaber, Geliebte, Prostituierte, Gigolo 
jan utala ali li ' nasa. :: Alle Soldaten sind blöd. 
jan utala li seli ala seli e tomo? :: Brannten die Krieger das Haus nieder? 
jan utala nasa :: blöder Soldat 
jan utala nasa mute :: viele blöde Soldaten 
jan utala pi ma Losi li ike, tawa ma ali. :: Russische Soldaten bringen der Welt Unheil. 
jan utala :: Soldat 
jan Wasintan [Washington] li ' jan lawa pona pi ma Mewika. :: Washington war ein guter Präsident der USA. 
jan wawa ala :: keine (einzige) starke Person 
jan wawa :: eine starke Person 
jan wawa pi pona mute li kama. :: Ein starker, sehr guter Mensch kommt. 
jan weka li kama. :: Der Abwesende kommt. 
jelo :: Adjektiv: gelb, hellgrün 
jelo :: gelb, hellgrün 
jelo :: Substantiv: Gelb, Hellgrün 
jo :: Adjektiv: privat, persönlich 
jo ala e selo lon pini palisa :: beschnitten 
jo e linja mute :: behaart, haarig 
jo e mani mute :: reich 
jo e pilin pona :: positive Gefühle haben, geistig gesund 
jo e selo lon pini palisa :: unbeschnitten 
jo e sijelo pona :: gesund 
jo (e ) :: Verb, transitiv: haben, enthalten, umfassen 
jo ijo mute li ike e jan. :: Viel Eigentum verdirbt Menschen. 
jo :: Substantiv: Besitz, Inhalt 
kala :: Adjektiv: fischig 
kala :: Fisch, Meeresfrüchte 
kala kule mute :: Der Regenbogenfisch 
kala lete :: roher Fisch, Sushi (Sashimi) 
Kalalinuna :: Grönland, Grönländisch 
kalama :: Adjektiv: laut, geräuschvoll, lautstark 
kalama ala li lon :: Kein Geräsch ist da.
kalama (e ) :: Verb, transitiv: klingen, läuten, klingeln, ein Instrument spielen 
kalama mu ni li ' pona, tawa mi. :: Dieser tierische Sound gefällt mir. 
kalama musi en meli li ' pona, tawa mi. :: Ich mag Musik und Frauen. 
kalama musi 'Jingle Bells' li ' pona, tawa mi. :: Ich mag das Lied 'Jingle Bells'. 
kalama musi li ' pona, tawa mi. :: Ich mag Musik. 
kalama musi :: Musik, Lied 
kalama musi pi jan Enja li ' pona. :: Enyas Musik ist gut. 
kalama musi pi jan Heino li ' nasa. :: Die Musik von Heino ist blöd. 
kalama pi kala ni li pakala e kala ali. :: Der Lärm dieses Fisches störte alle Fische. 
kalama :: Substantiv: Laut, Sound, Geräusch, Stimme 
kalama :: Verb, intransitiv: Geräusch machen, laut sein 
kala :: Substantiv: Wasserlebewesen, Fisch, Qualle, Tintenfisch, Muschel 
kala wawa li moku e soweli kala. :: Der Hai frisst die Robbe. 
kama :: Adjektiv: einkehrend, kommend, zukünftig 
kama :: Adverb: einkehrend, kommend, zukünftig 
kama (e ) :: Verb, transitiv: bewerkstelligen, herbeiführen 
kama :: Hilfsverb: werde(n), er- 
kama jo :: bekommen, erhalten 
kama jo (e ) :: Verb, transitiv: erhalten, bekommen, kriegen, abkriegen, nehmen 
kama :: kommen 
kama moli :: Verb, intransitiv: sterben 
kama olin :: sich verlieben (in ...) 
kama pona! :: Willkommen! 
kama sona (e ) :: Verb, transitiv: lernen, studieren 
kama :: Substantiv: Zukunft, Chance, Ankunft, Anreise, Anfang, Beginn 
kama :: Verb, intransitiv: kommen, werden, anfangen, eintreffen, ankommen, 
Kana :: Ghana 
Kanata :: Kanada 
Kanse :: Frankreich, Französisch 
kasi :: Adjektiv: vegetarisch, pflanzlich, biologisch 
kasi anpa :: Gras 
kasi (e ) :: Verb, transitiv: (ein-)pflanzen 
kasi :: Kräuter, Pflanzen 
kasi kule :: Blume 
kasi kule li ' pona lukin. :: Blumen sind schön. 
kasi kule loje lili :: The Little Pink Rose 
kasi li ' pona, tawa mi. :: Ich mag Blumen. 
kasi nasa :: berauschende Pflanze, z.B. Marihuana 
kasi nasa / kasi sona :: Hanf 
kasi sona :: berauschende Pflanze für Meditation, z.B. Marihuana 
kasi :: Substantiv: Pflanze, Blatt, Kraut, Baum, Strauch, Gras, Pilz 
kasi suli :: Baum, großer Strauch 
kasi suli li kasi, tawa sewi. :: Der Baum wächst in den Himmel. 
kasi :: Verb, intransitiv: (selber) wachsen 
kasi wawa :: Gewürze 
Katala :: Katar 
Katelo :: Georgien, Georgisch 
Katemala :: Guatemala 
Kenata :: Grenada 
ken (e ) :: Verb, transitiv: möglich machen, anordnen, aktivieren, freigeben, erlauben 
ken :: Hilfsverb: kann ... 
ken la ilo li ' pakala. :: Vielleicht ist das Werkzeug kaputt. 
ken la jan lili li wile moku e telo. :: Möglicherweise ist hat das Baby Durst. 
ken la jan Lisa li jo e ona. :: Vielleicht hat Lisa es. 
ken la jan Susan li kama. :: Vielleicht wird Susan kommen. 
ken la mi ken tawa ma Elopa. :: Vielleicht kann ich nach Europa gehen. 
ken la mi tawa. :: Vielleicht gehe ich. 
ken la ona li lape. :: Vielleicht schläft er. 
ken la ona li lon tomo sona. :: Vielleicht ist er in der Schule. 
ken la ) :: Substantiv: es besteht die Möglichkeit, bei Erlaubnis, bei Genehmigung 
ken la tenpo pimeja la ni li ' pona. :: Vielleicht, wenn es Nacht ist, ist dies gut. 
ken la tomo pi ona en sina pi jelo en loje li ' ike, tawa mi. :: Vielleicht mag ich das gelb-rot gemusterte Haus von ihr und dir nicht. 
ken :: Substantiv: Möglichkeit, Fähigkeit, Begabung, Erlaubnis, Genehmigung, Freigabe 
ken :: Verb, intransitiv: kann, ist fähig zu, ist bemächtigt zu, mögen; dürfen, ist möglich 
Kepeka :: Quebec 
kepeken ike pi ilo nasa :: Drogenmissbrauch 
kepeken lili pi ilo nasa :: geringer Drogenkonsum 
kepeken :: Präposition: mit, mittels, per 
kepeken :: Substantiv: Nutzung, Verwendung, Werkzeug 
kepeken utala :: Gewalt anwenden 
kepeken :: Verb, intransitiv: benutzen, verwenden, anwenden, nutzen, gebrauchen 
Keposi :: Zypern 
kili :: Adjektiv: fruchtig 
kili :: Adverb: fruchtig 
kili lili kiwen :: Nüsse 
kili lili :: kleines Obst bzw. Gemüse, Beere, Olive 
kili li lon poki. :: Die Früchte sind im Korb. 
kili li ' moku li ' pona. :: Ananas sind Nahrung und gut. 
kili li ' pona, tawa mi. :: Ich mag Obst. 
kili li tawa anpa, lon poka kasi. :: Der Apfel fällt nicht weit vom Stamm. 
kili loje :: rotes Obst bzw. Gemüse, Tomaten 
kili ma :: Erdfrucht, Kartoffel 
kili :: Obst, Gemüse 
kili palisa :: langes Obst/Gemüse, Möhre, Karotte, Banane, Gurke 
Kilipasi :: Kiribati 
kili pi jan Linta li ' ike. :: Lindas Früchte sind schlecht. 
kili pi jan Susan :: Susans Frucht 
kili seme en kili wan li ' kili # luka? :: Fünf Äpfel minus ein Apfel sind wieviel Äpfel? 
kili :: Substantiv: Frucht, Obst, Gemüse, Pilz 
kili suwi :: süße Frucht 
kili tu en kili wan li ' kili tu wan. :: Zwei Äpfel und ein Apfel sind drei Äpfel. 
kili tu tu en kili wan li ' kili seme? :: Zwei Äpfel und ein Apfel sind wieviel Äpfel? 
kin :: Adjektiv: auch, noch, ebenso, ferner, außerdem, gerade, wirklich, tatsächlich kin kann das letzte Wort in einer Adjektiv-Gruppe sein. 
kin :: Adverb: auch, noch, ebenso, ferner, außerdem, gerade, wirklich, tatsächlich kin kann das letzte Wort in einer Adverb-Gruppe sein. 
kin la :: Substantiv: wenn Wirklichkeit, wenn Tatsache 
Kinla :: Wales,Walisisch (Cymraeg) 
kin :: Substantiv: Wirklichkeit, Tatsache, Fakt 
kipisi (e ) :: Verb, transitiv (inoffiziell): schneiden 
kipisi :: Substantiv (inoffiziell): Abschnitt, Fragment, Scheibe 
kiwen :: Adjektiv: hart, schwer, heftig, fest, solid, stabil, robust, steinhart 
kiwen :: Adverb: hart, schwer, heftig, fest, solid, stabil, robust, steinhart 
kiwen (e ) :: Verb, transitiv: verfestigen, verhärten, versteinern 
kiwen :: Substantiv: Felsbrocken, Fels, Stein, Metall, Mineral, Lehm 
ko (e ) :: Verb, transitiv: zerquetschen, pulverisieren 
ko jaki :: Kot, Fäkalien, Scheiße, Kacke 
ko jaki lon nena sinpin :: Popel 
ko jaki :: Scheiße, Kacke, Kot, Fäkalien, pfui 
ko lete li kama :: es schneit 
kon :: Adjektiv: luftig, ätherisch, gasförmig, gasartig 
kon :: Adverb: luftig, ätherisch, gasförmig, gasartig 
kon en sewi :: Wetter 
kon (e ) :: Verb, transitiv: wegblasen 
Konko (pi ma tomo Kinsasa) :: Kongo, Dem. Rep. 
Konko (pi ma tomo Pasawi) :: Kongo, P. Rep. 
kon sewi li jo e walo :: es ist bewölkt, wolkig 
kon :: Substantiv: Luft, Atmosphäre, Wind, Odor, Geruch, Seele, Geist 
kon telo walo :: Schnee 
kon :: Verb, intransitiv: atmen 
Kosalika :: Costa Rica 
Kosiwa :: Côte d'Ivoire 
ko :: Substantiv: halbfeste Substanz, Paste, Puder, Gummi, Kleber, Mehl, Brei, Pulver 
ko (walo) wawa :: Kokain 
kule :: Adjektiv: farbenfreudig 
kule (e ) :: Verb, transitiv: färben, anstreichen, streichen 
kule :: Farben 
kule loje laso li ' pona, tawa mi. / :: Ich mag die Farbe Lila. 
kule lon palisa luka :: Nagellack 
kule seme li ' pona, tawa sina? :: Welche Farbe magst du? 
kule :: Substantiv: Farbe, Lack 
kulupu :: Adjektiv: kommunal, geteilt, öffentlich 
kulupu (e ) :: Verb, transitiv: montieren, zusammenbauen, zusammenrufen 
kulupu mama :: Familie 
kulupu pi kalama musi pi ma Inli li pona. :: Die englisch Rock-Band ist gut. 
kulupu pi ma Inli pi kalama musi li pona. :: Die englisch Rock-Band ist gut. 
kulupu pi toki pona :: die toki pona-Gemeinschaft 
kulupu :: Substantiv: Gruppe, Gemeinde, Gemeinschaft, Gemeinsamkeit, Gesellschaft 
Kupa :: Cuba 
Kusala :: Gujarat, Gujarati 
kute :: Adjektiv: auditiv, feinhörig 
kute (e ) :: Verb, transitiv: hören, zuhören 
kute :: Substantiv: Gehör, Hörsinn 
Kuwasi :: Kuweit 
Lanka :: Sri Lanka 
lape :: Adjektiv: schlafend 
lape :: Adverb: schlafend 
lape (e ) :: Verb, transitiv: bewusstlos schlagen 
lape li ' pona. :: Schlaf tut gut. 
lape pona! :: Schlaf gut! Gute Nacht! 
lape :: Substantiv: Schlaf, Ruhe, Pause 
lape :: Verb, intransitiv: schlafen, ruhen, dösen, liegen 
la :: Separator: Ein la trennt eine Konditional-Phrase von einem Satz. Verwende ein la nicht zusammmen mit einem der anderen Separatoren. 
laso :: Adjektiv: blau, cyan 
laso :: blau, blaugrün 
laso jelo li ' pona, tawa mi. :: Grün ist meine Lieblingsfarbe. 
laso loje li ' pona, tawa mi. :: Lila ist meine Lieblingsfarbe. 
laso pimeja :: dunkelblau 
laso :: Substantiv: Blau, Cyan 
lawa :: Adjektiv: Haupt- , größt- , wichtigst-, Leit-, tonangebend 
lawa :: Adverb: führend, 
lawa e pilin :: seine Gefühle im Griff haben, sich beherrschen, gelassen, gefasst 
lawa (e ) :: Verb, transitiv: führen, lenken, kontrollieren, steuern, herrschen 
lawa :: Kopf 
lawa :: Substantiv: Kopf, Sinn, Meinung, Ansicht 
len :: Adjektiv: gekleidet, kostümiert, verkleidet 
len (e ) :: Verb, transitiv: (Kleidung) tragen, verkleiden 
len :: Kleidung, Leinen, Stoff, Tuch 
len kule li ' pona, tawa mi. :: Mir gefällt das bunte Kleid. 
len lawa :: Hut, Haube, Kapuze, Mütze, Frisur 
len loje laso mi li ' pona, tawa mi. :: Dieses lila T-Shirt gefällt mir. 
len luka :: Handschuhe 
len ni li kule seme? :: Welche Farben hat dieses Kleidungsstück? 
len ni pi loje en laso li ' pona, tawa mi. :: Dieses rot und blau gemusterte T-Shirt gefällt mir. 
len noka :: Schuhe, Hose, Strümpfe 
len pi jan Lisa :: Lisas Kleidung 
len pi jan Susan li ' jaki. :: Susans Kleider sind dreckig. 
len pi loje en laso pi meli sina li ' pona, tawa mi. :: Das rot und blau gemusterte Kleid deiner Frau geällt mir. 
len sina li ' telo ala ' telo? :: Sind deine Kleider nass? 
len :: Substantiv: Kleidung, Bekleidung, Stoff, Tuch, Lappen, Gewebe, Netzwerk, Internet 
Lesi :: Bretagne, Bretonisch 
lete :: Adjektiv: kalt, frostig, roh, ungekocht 
lete :: Adverb: trostlos 
lete (e ) :: Verb, transitiv: erkalten, kühlen, gefrieren, vereisen 
lete lili li lon. :: Es ist kühl. 
lete li lon :: es ist kalt 
lete li lon. :: Es ist kalt. 
lete mute li lon. :: Es ist sehr kalt. 
lete :: Substantiv: Kälte 
lili :: Adjektiv: klein, gering, unbedeutend, wenig, kaum, schwerlich, jung, ein wenig, kurz 
lili :: Adverb: wenig 
lili (e ) :: Verb, transitiv: verkleinern, verringern, ermäßigen, schrumpfen 
lili :: klein, kurz, dünn, jung 
lili :: Substantiv: Kleinheit, Jugend, Unmündigkeit 
linja :: Adjektiv: länglich, rechteckig, lang 
linja (lawa) :: Haare 
linja lawa :: Haare (Kopf-) 
linja lili oko :: Augenbrauen, Augenwimpern 
linja mi li ' telo. :: Mein Haar ist naß. 
linja sinpin :: Bart, Gesichtshaar 
linja :: Substantiv: Faden, Kette, Saite, Schnur, Sehne, Leine, Haar, Zwirn 
linja uta :: Schnurrbart 
Lipija :: Libyen 
lipu :: Adjektiv: Buch-, Papier-, Karten-, Ticket-, Bogen-, Seiten- 
lipu ni li ' lete, tawa mi. :: Dieses Papier fühlt sich kalt an. 
lipu :: Substantiv: Schriftstück, z.B. Papier, Pappe, Karte, Ticket, Website, Blog, Liste 
lipu toki :: Bericht 
lipu toki :: Dokument, Text, Buch, Zeitung, Zeitschrift, Website 
Lisensan :: Liechtenstein 
li :: Separator: Er trennt die Subjekt-Phrase, außer mi und sinavon, von der Prädikat-Phrase. Verwende ein li nicht zusammmen mit einem der anderen Separatoren. 
loje :: Adjektiv: rot, rötlich 
loje jelo li ' pona, tawa mi. :: Orange ist meine Lieblingsfarbe. 
loje laso li ' pona, tawa mi. :: Lila ist meine Lieblingsfarbe. 
loje laso (pimeja) :: (dunkles) Purpur, lila 
loje :: rot 
loje :: Substantiv: Rot 
loje walo li ' pona, tawa mi. :: Rosa ist meine Lieblingsfarbe. 
loje walo :: rosa, rosarot 
Lomani :: Rumänien, Rumänisch 
lon :: Adjektiv: real, wahr, bestehend, richtig, echt 
lon (e ) :: Verb, transitiv: gebären, erschaffen 
lon ona la mi ken lukin e ona. :: Hat es ein Sein, können wir es auch sehen. 
lon ona la ni li ' pona, tawa mi. :: Wenn es existiert, ist es gut für mich. 
lon :: Präposition: in, im, an, am, bei, auf 
lon :: Substantiv: Existenz, Sein, Präsenz 
lon tenpo pi pali ala :: Urlaub, Studienurlaub 
lon :: Verb, intransitiv: anwesend sein, vorhanden sein, enthalten sein, existieren, leben 
Losi :: Russland, Russisch 
Lowasi :: Kroatien, Kroatisch 
Lowenki :: Slowakei, Slowakisch 
Lowensina :: Slowenien, Slowenisch 
luka :: 5 
luka :: Adjektiv: greifbar, Tast- 
luka :: Adjektiv, Ziffer: fünf, 5 
luka :: Hand, Arm 
luka luka :: 5 + 5 = 10 
luka luka luka :: 5 + 5 + 5 = 15 
luka luka tu :: 5 + 5 + 2 = 12 
luka luka tu tu :: 5 + 5 + 2 + 2 = 14 
luka luka tu wan :: 5 + 5 + 2 + 1 = 13 
luka luka wan :: 5 + 5 + 1 = 11 
luka mi li ' jaki. mi wile telo e ona. :: Meine Hände sind dreckig. Ich möchte sie waschen. 
luka :: Substantiv: Hand, Arm 
luka tu :: 5 + 2 = 7 
luka tu tu :: 5 + 2 + 2 = 9 
luka tu wan :: 5 + 2 + 1 = 8 
luka wan :: 5 + 1 = 6 
lukin :: Adjektiv: optisch, sichtbar, visuell 
lukin :: Adverb: optisch, sichtbar, visuell 
lukin :: bewusst, bemerken, aufmerksam, aufpassen 
lukin e toki :: lesen 
lukin (e ) :: Verb, transitiv: sehen, betrachten, lesen 
lukin :: Hilfsverb: sehen 
lukin jo e pali :: auf Arbeitssuche 
lukin :: Substantiv: Sicht, Blick, Sehen, Vision 
lukin :: Verb, intransitiv: aussehen, aufpassen (auf), Ausschau halten (nach), achten auf 
Lunpan :: Libanon 
lupa :: Adjektiv: löchrig 
lupa (e ) :: Verb, transitiv: durchbohren, erstechen, perforieren 
lupa jaki :: After 
lupa kute :: Ohr, Gehör 
lupa :: Loch, Mündung 
lupa meli :: Scheide, Vagina 
lupa meli :: Vagina 
lupa monsi :: After, Anus 
lupa nena :: Nasenlöcher, Nüstern 
lupa ni li ' suli. :: Das Loch ist groß. 
lupa pi telo jelo :: Harnröhrenöffnung 
lupa :: Substantiv: Loch, Höhle; Bau, Mündung, Öffnung, Ausguss, Fenster, Tür, Tor 
lupa (tomo) :: Fenster, Tür 
Lusepu :: Luxemburg 
Luwanta :: Ruanda 
ma :: Adjektiv: ländlich, im Freien, Open-Air- 
ma ali li ' pona, tawa mi. :: Für mich sind alle Länder gut. 
ma Elopa li ' pona. :: Europa ist gut. 
ma Epanja :: Spanien 
ma Italija li ' pona lukin. :: Italien ist schön. 
ma Kanata li ' pona. :: Kanada ist gut. 
ma kasi :: Wald, Dschungel 
Maketonija :: Mazedonien; Makedonien 
ma :: Ökologie 
Malakasi :: Madagaskar, Malagasy 
Malasija :: Malaysia, Malaiisch 
Malawi :: Malawi 
ma li lon anpa mi. :: Das Land ist unter mir. 
ma li lon noka mi. :: Land ist unter meinen Füßen. 
Mali :: Mali 
Malipe :: Marokko 
ma li pona lukin. :: Die Landschaft ist schön anzuschauen. 
mama :: Adjektiv: elterlich, mütterlich, väterlich 
mama :: Eltern (Vater und/oder Mutter) 
mama (e ) :: Verb, transitiv: bemuttern 
mama meli :: Mutter 
mama meli :: Mutter, Mama 
mama meli o awen! :: Warte Mutti! 
mama mije :: Vater 
mama mije :: Vater, Papa 
mama mi li ' moli la mi pilin ike. :: Wenn meine Eltern sterben, fühle ich mich schlecht. 
mama :: Mutter, Vater, Eltern 
mama ona li kepeken kasi nasa. :: Seine Mutter verwendete Marihuana. 
mama pi mama mi :: meine Großeltern, meine Oma, mein Opa 
mama :: Substantiv: Eltern, Mutter, Vater 
ma mi li ' pimeja. :: Mein Land ist dunkel. 
ma mi li ' Tosi. :: Meine Heimat ist Deutschland. 
mani :: Adjektiv: Finanz-, finanziell, Währungs-, Vermögens- 
mani :: Adverb: finanziell 
mani pi ma ante li ' pona, tawa mi. :: Ich mag die Währungen anderer Länder. 
mani :: Substantiv: Geld, Währung, Euro, Kapital 
ma pi jan Keli :: Kellys Land 
ma seme li ' pona, tawa sina? :: Welche Länder magst du? 
Masija :: Ungarn, Ungarisch 
ma sina :: dein Land 
ma :: Substantiv: Land, Gegend, Erde, Staat, Kontinent, Gebiet, Zone, Areal 
Masu :: Ägypten 
ma suli Amelika :: Amerika 
ma suli Amelika lete :: Nord-Amerika 
ma suli Amelika seli :: Süd-Amerika 
ma suli Antasika :: Antarktis 
ma suli Apika :: Afrika 
ma suli Asija :: Asien 
ma suli Elopa :: Europa 
ma telo :: Schlamm, Sumpf, Moor 
ma tomo Akajela :: Al-Qahirah, Kairo (Hauptstadt von Ägypten) 
ma tomo Alana :: Atlanta (Stadt in den USA) 
ma tomo Alawa :: Ottawa (Hauptstadt von Kanada) 
ma tomo Alenta :: Atlanta 
ma tomo Alipasi :: Halifax (Stadt in Kanada) 
ma tomo Anpu :: Hamburg (Stadt in Deutschland) 
ma tomo Ansetan :: Amsterdam (Hauptstadt der Niederlande) 
ma tomo Asina :: Athen (Hauptstadt von Griechenland) 
ma tomo Ele :: Los Angeles (Stadt in den USA) 
ma tomo Esupo :: Espoo (Stadt in Finnland) 
ma tomo Iwesun :: Hilversum (Netherlands) 
ma tomo Kakawi :: Calgary (Stadt in Kanada) 
ma tomo Kenpisi :: Cambridge (Stadt in den USA bzw. GB) 
ma tomo Kunte :: Krung Thep; Bangkok (Hauptstadt von Thailand) 
ma tomo Lantan li ' suli. :: London ist groß. 
ma tomo Lanten :: London 
ma tomo Lanten :: London (Hauptstadt von Großbritannien und Nordirland) 
ma tomo lawa :: Haupstadt 
ma tomo Lesinki :: Helsinki; Helsingfors (Hauptstadt von Finnland) 
ma tomo Loma :: Rom 
ma tomo Loma :: Rom (Hauptstadt von Italien) 
ma tomo Manten :: Moncton (Stadt in Kanada) 
ma tomo Mesiko :: Mexiko-Stadt (Hauptstadt von Mexiko) 
ma tomo Milano :: Mailand (Stadt in Italien) 
ma tomo mi li ' Pelin. :: Meine Heimatstadt ist Berlin. 
ma tomo Minsen :: Munich (Stadt in Deutschland) 
ma tomo Monkela :: Montreal (Stadt in Kanada) 
ma tomo Napoli :: Napoli, Neapel (Stadt in Italien) 
ma tomo Nujoka :: New York City (Stadt in den USA) 
ma tomo Osaka :: Osaka (Stadt in Japan) 
ma tomo Paki :: Paris (Hauptstadt von Frankreich) 
ma tomo Pasen :: Boston (Stadt in den USA) 
ma tomo Pelin :: Berlin 
ma tomo Pelin :: Berlin (Hauptstadt von Deutschland) 
ma tomo Peminan :: Birmingham (Stadt in England) 
ma tomo Pesin :: Beijing; Peking (Hauptstadt von China) 
ma tomo Pilense :: Florenz (Stadt in Italien) 
ma tomo Polan :: Portland (Stadt in den USA) 
ma tomo Putapesi :: Budapest (Hauptstadt von Ungarn) 
ma tomo Sakata :: Jakarta (Hauptstadt von Indonesien) 
ma tomo Sanpansiko :: San Francisco 
ma tomo Sanpansiko :: San Francisco (Stadt in den USA) 
ma tomo Sawi :: Sackville (Stadt in Kanada) 
ma tomo Sene :: Genf (Schweiz) 
ma tomo Sensan :: St. John's (Stadt in Kanada) 
ma tomo Sesija :: Shediac (Stadt in Kanada) 
ma tomo Sije :: Dieppe (Stadt in Kanada) 
ma tomo Solu :: Seoul (Hauptstadt der Republik Korea) 
ma tomo :: Stadt, Kleinstadt, Dorf 
ma tomo :: Städte 
ma tomo Tanpele :: Tampere (Finnland) 
ma tomo Telawi :: Tel Aviv (Stadt in Israel) 
ma tomo Tokijo :: Tokyo; Tokio (Hauptstadt von Japan) 
ma tomo Towano :: Toronto (Stadt in Kanada) 
ma tomo Tuku :: Turku (Stadt in Finnland) 
ma tomo Wankuwa :: Vancouver (Stadt in Kanada) 
ma tomo Wenesija :: Venedig (Stadt in Italien) 
ma Tosi :: Deutschland 
meli :: Adjektiv: weiblich, feminin, fraulich 
meli en mije :: Frauen und Männer 
meli esun li pana e pan, tawa mi. :: Die Verkäuferin gibt mir das Brot. 
meli Italija :: Italienerin 
meli kala lili li tawa e ona, lon telo. :: Die Meerjungfrau schwimmt im Wasser. 
meli lili :: Tochter 
meli li lon e jan lili ona. :: Die Frau gebahr ihr Kind. 
meli li lon sewi mije :: Mann unten, Frau oben 
meli li nasa e mije. :: Frauen machen Männer verrückt. 
meli Mawija :: Maria 
meli mi li namako e moku. :: Meine Frau würzt das Essen. 
meli mi nanpa wan li ' nasa. :: Meine erste Freundin war verrückt. 
meli (olin) :: Ehefrau, Verlobte, Braut, Geliebte, Partnerin, Freundin 
meli olin ona li ' pona lukin. :: Seine Frau ist hübsch. 
meli pi pana moku :: Kellnerin 
meli sama :: Schwester 
meli :: Substantiv: Frau, Dame, Lady, Mädchen, Weibchen, Weib, Ehefrau, Freundin 
meli unpa :: Geliebte, Liebhaberin, Gespielin, sexy Mädchen 
Mesiko :: Mexiko 
Mewika :: USA 
mi anpa e jan utala. :: Ich besiegte den Soldaten. 
mi awen sona e ni. :: Ich erinnere mich daran. 
mi en meli mi li ' wan. :: Meine Freundin und ich sind verheiratet. 
Mijama :: Myanmar 
mi ' jan Ken. / nimi mi li Ken. :: Mein Name ist Ken. 
mi ' jan li ' suli. :: Ich bin ein Mensch und bedeutend. 
mi ' jan Pepe. :: Ich bin Pepe. 
mi ' jan pi toki pona. :: Ich bin ein Toki-Ponianer. 
mi ' jan \`\`Robert". :: Ich bin Robert. 
mi ' jan "Robert". :: Ich bin Robert. 
mije :: Adjektiv: männlich, maskulin 
mije Epanja :: Spanier 
mije lili :: Sohn 
mije li lon sewi meli :: Missionarsstellung 
mije (olin) :: Ehemann, Verlobte, Bräutigam, Liebhaber, Partner, Freund 
mije sama :: Bruder 
mije :: Substantiv: Mann, Kerl, Ehemann, Liebhaber 
mije unpa :: Geliebter, Liebhaber 
mi jo e ilo. :: Ich habe ein Werkzeug. 
mi jo e kili. :: Ich habe Früchte. 
mi jo e ni. :: Dies ist meins. 
mi jo e tomo tawa sina. mi pana e ni tawa sina. :: Ich habe dein Auto. Ich gebe es dir. 
mi jo e tomo tawa tu. :: Ich besitze zwei Autos. 
mi kalama e kalama musi, kepeken ilo. :: Ich mache Musik mit einem Instrument. 
mi kama e pakala. :: Ich verursachte einen Unfall. 
mi kama jo e telo. :: Ich bekam das Wasser. 
mi kama sona e ni. :: Ich lerne dies. 
mi kama, tan ma Mewika. :: Ich komme aus Amerika. 
mi kama, tan ma suli Elopa. :: Ich komme aus Europa. 
mi kama, tan ma tomo Pelin. :: Ich komme aus Berlin. 
mi kasi e kasi kule, lon poki. :: Ich pflanze die Blume in den Topf. 
mi ken ala kute e toki sina. :: Ich kann nicht hören, was du sagst. 
mi ken ala lape. :: Ich kann nicht schlafen. 
mi kepeken ilo. :: Ich benutze ein Werkzeug. 
mi kepeken poki li kepeken ilo moku. :: Ich verwende eine Schüssel und einen Löffel.
mi kepeken poki ni. :: Ich nehme diese Tasse. 
mi kon e ilo suno. :: Ich puste die Kerze aus. 
mi kule e len. :: Ich färbe das Kleid. 
mi kute e kalama musi. :: Ich höre Musik. 
mi kute e toki sina. :: Ich hörte dich sprechen. 
mi lape ala. :: Ich schlafe nicht. 
mi lape la ali li ' pona. :: Wenn ich schlafe, ist alles gut. 
mi lape. mi sona. :: Ich schlafe. Ich weiss. 
mi lawa pona e jan. :: Ich führe Menschen gut. 
mile moku e telo :: durstig sein 
mi li lukin lili e ona. :: Ich sah es kaum. 
mi lon ma kasi. :: Ich bin im Wald. 
mi lon mute tomo. :: Ich bin oft im Haus. 
mi lon, tan seme? :: Warum bin ich hier? 
mi lon tenpo ni. :: Ich existiere jetzt. 
mi lon tomo. :: Ich bin im Haus. 
mi lukin ala e poki laso. :: Ich sehe die blaue Tasche nicht. 
mi lukin e ma, lon poka pi jan pona mi. :: Ich schaue mir das Land mit meinem Freund an. 
mi lukin e ma, lon poka sina. :: Ich schaue mir das Land mit dir an. 
mi lukin e ma. ni li ' pona, tawa mi. :: Ich schaue mir die Landschaft an. Das ist gut für mich. 
mi lukin e mije anu meli. :: Ich sehe einen Mann oder eine Frau. 
mi lukin e ni. :: Ich betrachte es. 
mi lukin e soweli luka. :: Ich sah fünf Pferde. 
mi lukin e waso tu wan. :: Ich sah drei Vögel. 
mi lukin, kepeken ilo suno. :: Ich sehe mittels Taschenlampe. 
mi lukin sewi e tomo suli. :: Ich schaue hoch zum Wolkenkratzer. 
mi lukin taso e meli ni! :: Ich habe mir nur das Mädchen angeschaut. 
mi moku e kili e telo. :: Ich verspeise/trinke die Frucht und das Wasser. 
mi moku e kili e telo li lukin e ma e jan. :: Ich verspeise Früchte und Wasser und sehe Land und Menschen. 
mi moku e kili. :: Ich esse Früchte. 
mi moku e moku li lukin e ma. :: Ich esse das Essen und betrachte die Landschaft. 
mi moku e pan namako. :: Ich esse das würzige Brot. 
mi moku e telo, lon tenpo ni. :: Ich trinke jetzt. 
mi ' moku. :: Ich bin eine Mahlzeit. 
mi moku. :: Ich esse. 
mi moku, kepeken ilo moku. :: Ich esse mit Besteck. 
mi moku lili e kili lili. :: Ich nasche ein wenig von den kleinen Früchten. 
mi moku lili e moku soweli. :: Ich esse wenig Fleisch. 
mi moku li pakala. :: Ich esse und zerstöre. 
mi moku, lon poka sina. :: Ich esse an deiner Seite. 
mi moku, lon tomo. :: Ich esse im Haus. 
mi moku mute. sina moku lili. :: Ich esse mehr als du. 
mi moku, tan ni: mi wile moku. :: Ich esse weil ich hungrig bin. 
mi musi ala. :: Ich amüsiere mich nicht. 
mi musi taso. :: Ich scherzte nur. 
mi mute li moku e telo nasa mute. :: Wir tranken viel Wodka. 
mi mute li pana e moku, tawa ona mute. :: Wir gaben ihnen Essen. 
mi mute lukin mute e ma. :: Ich vergrößere gut sichtbar das Land. 
mi mute o moku e kala. :: Lass uns Fisch essen. 
mi mute o ' musi! :: Laß uns Spaß haben. 
mi mute o tawa! :: Laß uns gehen. 
mi mute :: wir, uns 
mi nanpa e mani mi, lon esun suli. :: Ich zähle mein Geld in einem Supermarkt. 
mi olin e sina :: Ich liebe dich. 
mi olin e sina. :: Ich liebe dich. 
mi olin kin e sina. :: Ich liebe dich auch / immer noch.
mi open sona e ni. :: Ich beginne dies zu begreifen. 
mi pakala e pipi ike. :: Ich verletzte das eklige Insekt. 
mi pali mute la mi pilin ike. :: Wenn ich viel arbeite, fühle ich mich schlecht. 
mi pali taso. :: Ich arbeite nur. 
mi pana e ko jaki. :: Ich habe ein großes Geschäft gemacht. 
mi pana e telo jelo. :: Ich urinierte. 
mi :: Personalpronomen: ich, wir 
mi pilin e ijo. :: Ich denke über etwas nach. 
mi pilin e meli ni. :: Ich denke über diese Frau nach. 
mi pilin e ni: ona li jo ala e mani. :: Ich denke, dass er kein Geld hat. 
mi pilin e ni: sina ike. :: Ich denke, daß du böse bist. 
mi pilin e seli sijelo sina. :: Ich fühle deine Körperwärme. 
mi pilin ike. :: Ich fühle mich schlecht/traurig. 
mi pilin lete. :: Ich friere. 
mi pilin lete mute. :: Mir ist sehr kalt. 
mi pilin pona. :: Ich fühle mich gut. 
mi pini sona e ni. :: Ich habe dies vergessen. 
mi ' pona ala ' pona, tawa sina? :: Magst du mich? 
mi pona e ale mi la mi pona e mi. :: Wenn ich alles um mich verbessere, verbessere ich mich selber. 
mi pona e ijo. :: Ich repariere etwas. 
mi pona e ilo suno, kepeken ilo lili. :: Ich reparierte die Taschenlampe mit einem kleinen Werkzeug. 
mi pona e tomo, tawa jan pakala. :: Ich reparierte das Haus für den behinderten Mann. 
mi pona e tomo tawa, kepeken ilo ni. :: Ich repariere das Auto mit diesem Werkzeug. 
mi pona e tomo tawa. mi kepeken ilo ni. :: Ich reparier das Auto. Ich verwende dieses Werkzeug. 
mi pona e tomo tawa. mi wile kepeken ilo ni. :: Ich reparier das Auto. Ich möchte dieses Werkzeug verwenden. 
mi ' pona, tan ni: mi lon. :: Mir geht es gut,weil ich lebe. 
mi ' pona. taso meli mi li ' pakala. :: Ich bin OK aber meine Freundin ist verletzt. 
mi ' pona, tawa sina anu seme? :: Magst du mich? 
mi :: Possessivpronomen: mein, unser 
mi seme e jan telo nasa? :: What Shall We Do With The Drunken Sailor? 
mi sewi. :: Ich stehe auf. 
mi sitelen e sitelen, lon lipu. :: Ich male das Bild auf Papier. 
mi sona ala e nimi pi ona mute. :: Ich kenne nicht ihre Namen. 
mi sona e ni, lon kama. :: Ich werde es wissen. 
mi sona e ni, lon tenpo kama. :: Ich werde es wissen. 
mi sona e ni taso. :: Das ist alles was ich weiß. 
mi sona e tan. :: Ich kenne die Ursache. 
mi sona kama e ni. :: Ich lerne dies. 
mi sona kama e ni. :: Ich weiß, wie man dorthin kommt. 
mi ' suli. :: Ich bin wichtig. / Ich bin fett. 
mi ' suli mute. sina ' suli lili. :: Ich bin größer als du. 
mi taso li lon. :: Nur ich bin da. 
mi tawa e kiwen, tawa sewi. :: Ich bewege den Felsen zum Gipfel. 
mi tawa e mi, tawa noka sina. :: Ich verneige mich vor dir. 
mi tawa e mi, tawa tomo mi. :: Ich bewege mich zu meinem Haus. 
mi tawa! :: Ich gehe! Tschüss! Auf Wiedersehen! 
mi tawa, lon poka sina. :: Ich gehe an deiner Seite. 
mi tawa supa lape. :: Ich gehe ins Bett. 
mi tawa, tan sina. :: Ich verlasse dich. 
mi tawa, tawa sina. :: Ich gehe zu dir. 
mi tawa, tawa tomo mi. :: Ich gehe zu meinem Haus. 
mi tawa, tawa tomo pi telo nasa. :: Ich ging in die Kneipe. 
mi tawa, tawa tomo toki. ona li pona, tawa mi. :: Ich gehe in den Chat-Room. Es gefällt mir. 
mi tawa! :: Tschüss! 
mi tawa weka e mi. :: Ich bewege mich weg. 
mi telo e mi. :: Ich wasche mich. 
mi telo e mi, lon tomo telo. :: Ich wasche mich im Badezimmer. 
mi toki, tawa sina. :: Ich spreche zu dir. 
mi utala ike. :: Ich kämpfe schlecht. 
mi wawa ala. :: Ich bin nicht stark. 
mi weka e ijo tu ni. :: Ich entfernte diese beiden Dinge. 
mi ' weka. :: Ich war weg. 
mi wile ala e ijo. mi lukin taso. :: Ich möchte nichts. Ich schaue nur. 
mi wile ala pali. :: Ich bin faul. 
mi wile ala tawa musi. :: Ich möchte nicht tanzen. 
mi wile ala toki, tawa sina. :: Ich möchte nicht mit dir reden. 
mi wile e ilo moku. :: Ich brauche eine Gabel. 
mi wile e ni: mi lon tomo. :: Ich will dies: Ich bin zu Hause. 
mi wile e sitelen ma. :: Ich brauche die Landkarte. 
mi wile e soweli lili. :: Ich möchte einen Hamster haben. 
mi wile e suwi! :: Ich will einen Keks. 
mi wile e suwi sin! :: Ich möchte noch einen Keks. 
mi wile kama sona e toki Inli. :: Ich möchte Englisch lernen. 
mi wile kin tawa, tawa tomo mi. :: Ich will noch in mein Haus gehen. 
mi wile lon tomo. :: Ich möchte im Haus sein. 
mi wile, lon tomo. :: Ich will etwas im Haus. 
mi wile lon tomo. :: Ich will zu Hause sein. / Ich will etwas im Haus. 
mi wile lukin e ma ante. :: Ich möchte andere Länder sehen. 
mi wile lukin e ma e suno. :: Ich will das Land und die Sonne sehen. 
mi wile lukin e ma. :: Ich möchte die Landschaft sehen. 
mi wile lukin e tomo mi. taso mi lon ma ante. :: Ich möchte mein Haus sehen aber ich bin in einem anderen Land. 
mi wile moku e kili loje. :: Ich möchte eine rote Frucht essen. 
mi wile moku e waso. :: Ich will Hühnchen essen. 
mi wile moku. taso mi jo ala e moku. :: Ich habe Hunger aber ich habe nichts zu essen. 
mi wile pakala e sina. :: Ich muss dich vernichten. 
mi wile pana e ko jaki. :: Ich muß kacken. 
mi wile pana e telo jelo. :: Ich muß pullern. 
mi wile sin e telo pi lape ala. :: Ich brauche mehr Kaffee. 
mi wile tawa. taso mi ken ala. :: Ich möchte gehen, aber ich kann nicht. 
mi wile tawa, tawa ma suli Oselija. :: Ich möchte nach Australien gehen. 
mi wile tawa, tawa ma Tosi. :: Ich möchte nach Deutschland reisen. 
mi wile tawa tomo ona, kepeken tomo tawa mi. :: Ich möchte mit meinem Auto zu seinem Haus fahren. 
mi wile toki meli. :: Ich möchte über Mädchen sprechen. 
mi wile unpa e sina :: Ich möchte mit dir schlafen. 
moku :: Adjektiv: essend 
moku :: Adverb: essend 
moku :: Essen, Mahlzeit, Getränk, essen, trinken 
moku e telo nasa :: Alkohol trinken, saufen 
moku e telo :: trinken 
moku (e ) :: Verb, transitiv: essen, trinken, schlucken, verzehren, verspeisen 
moku lili :: Imbiss, Vesper, Jausenbrot, Snack 
moku lili :: Pille, Tablette, Medikament 
moku lili pi pilin pona mute :: stark euphorisierende Droge (Tablette), z.B. MDMA 
moku li lon insa mi. :: Das Essen ist in meinem Inneren. 
moku li ' pona. :: Das Essen ist gut. 
moku li pona, tawa ona. :: Er liebt es zu essen. 
moku pona! :: Guten Appetit! Mahlzeit! 
moku :: Substantiv: Essen, Lebensmittel, Nahrung, Nahrungsmittel, Mahlzeit, Fressen 
moku suwi :: Süßigkeit, Konfekt, Praline, Bonbon, Schokolade 
moku telo :: flüssiges Essen, Suppe 
moku walo :: weißes Essen, Reis 
moli :: Adjektiv: tot, tödlich, fatal, schwerwiegend 
moli :: Adverb: tödlich 
moli (e ) :: Verb, transitiv: töten 
moli li ' ike, tawa jan ali. :: Der Tod ist schlecht für alle Menschen. 
moli :: Substantiv: Tod, Todesfall 
moli :: Verb, intransitiv: tot sein 
monsi :: Adjektiv: Rück-, Hinter- 
monsi :: Hintern, Po 
monsi :: Po, Pobacken, Hintern 
monsi :: Rücken, Hintern 
monsi :: Substantiv: Rücken, Heck, Hintern, Po, Arsch 
monsuta :: Adjektiv (inoffiziell): ängstlich 
monsuta :: Substantiv (inoffiziell): Monster, Ungeheuer, Fabelwesen, Angst 
monsuta waso pi pan linja li pali e ali. :: Das Fliegende Spaghettimonster erschuf die Welt. 
Motowa :: Moldawien 
mu :: Adjektiv: Tiergeräusch- 
mu :: Adverb: Tiergeräusch- 
mu (e ) :: Verb, transitiv: Tiergeräusche machen 
mu! :: Interjektion: Wau!, Miau!, Muh! (Tiergeräusch) 
Mulitanija :: Mauretanien 
mu! :: Määh (Schaf). 
mu! :: Muh! Wau! Miau! 
mu! mu! mu! :: Wau! Wau! Wau! 
mu! :: Mu! Wau! Miau! (Tiergeräusche) 
mun :: 
mun :: Adjektiv: Mond- 
mu ni li ' ike a! :: Dieses Bellen ist ja schrecklich! 
mun li pimeja (ale) :: Neumond 
mun li pimeja e suno :: Sonnenfinsternis 
mun li sike (ale) :: Vollmond 
mun :: Substantiv: Mond, Stern, Planet 
musi :: Adjektiv: kunstvoll, spaßig, Erholung-, Freizeit- 
musi :: Adverb: fröhlich 
musi (e ) :: Verb, transitiv: amüsieren, unterhalten, belustigen, bewirten 
musi pona! :: Viel Spaß! 
musi :: Substantiv: Spaß, Partie, Spiel, Freizeit, Erholung, Kunst, Unterhaltung 
musi :: Verb, intransitiv: spielen, Spaß haben 
mu :: Substantiv: Tiergeräusch 
mute :: Adjektiv: viel, viele, mehrere, sehr, reichlich, zahlreich, weiter, 
mute :: Adjektiv, Ziffer: 20 (offizielles Toki Pona Buch) 
mute :: Adverb: viel, sehr, reichlich, zahlreich, mehr, weiter, 
mute (e ) :: Verb, transitiv: viel machen, vermehren 
mute :: Substantiv: Betrag, Summe, Menge, Quantität 
mute wan :: 20 + 1 = 21 (Wird selten verwendet.) 
mu :: Verb, intransitiv: tierisch kommunizieren 
namako :: Adjektiv: würzig, pikant 
namako (e ) :: Verb, transitiv: würzen 
namako :: Substantiv: Gewürz, Salz, Nahrungsergänzung, Kräuter 
Namipija :: Namibia 
nanpa :: Adjektiv, Ziffer: Zum Bilden von Ordnungszahlen. 
nanpa (e ) :: Verb, transitiv: zählen, nummerieren, beziffern, rechnen 
nanpa :: Substantiv: Zahl, Ziffer, Anzahl, Ordnungszahl 
nasa :: Adjektiv: dumm, doof, blöd, töricht, albern, verrückt, übergeschnappt 
nasa :: Adverb: töricht, affig, albern, verrückt, übergeschnappt 
nasa (e ) :: Verb, transitiv: verrückt machen 
nasa lukin :: komisch aussehend 
nasa pona! :: Prost! 
nasa :: Substantiv: Dummheit, Unsinn, Blödsinn, Stumpfheit, Schussel, Wirrkopf 
nasa :: verrückt, übergeschnappt, töricht, närrisch, albern 
Naselija :: Nigeria 
nasin :: Adjektiv: systematisch, gewöhnlich, üblich 
nasin ale :: Wege des Lebens 
nasin ante li ' pona, tawa jan ante. :: Jeder geht seinen Weg. 
nasin li jo e telo kiwen. :: Die Straßen sind glatt (gefroren). 
nasin mani li ' ike. :: Der Kapitalismus ist schlecht. 
nasin pi anpa suno :: Westen 
nasin pi kama suno :: Osten 
nasin pi toki pona :: die Ideologie von toki pona 
nasin pona Juju :: Universalismus 
nasin pona Lasapali :: Rastafarismus 
nasin pona Latapali :: Rastafarianismus 
nasin pona li ' mute. :: Es gibt viele Arten, Gutes zu tun. 
nasin pona :: Taoism, Primitivismus 
nasin pona :: Taoismus 
nasin sewi Jawatu :: Judaismus 
nasin sewi Jawatu :: Judentum 
nasin sewi Kolisu :: Christentum 
nasin sewi ma :: Erdreligion, Indianerglauben, heidnischer Glauben 
nasin sewi Patapali :: Pastafari 
nasin sewi Puta :: Buddhismus
nasin sewi Puta :: Buddhismus 
nasin sewi :: Religionen 
nasin sewi Silami :: Islam 
nasin :: Substantiv: Weg, Straße, Strecke, Pfad, Methode, Doktrin, Lehre, System 
nasin tawa pi jan Nuton :: die Newtonsches Gesetze 
nena :: Adjektiv: hügelig, bergig, bucklig, holprig 
nena kon :: Nase 
nena kute :: Ohr 
nena (lawa) :: Nase 
nena lili pi nena mama :: Brustwarzen 
nena lili (unpa) meli :: Kitzler, Klitoris 
nena mama, nena meli :: Brüste 
nena meli :: Brüste 
nena sike meli :: weibliche Brust 
nena :: Substantiv: Beule, Hügel, Berg, Gebirge, Erhebung, Button, Nase, Rundung 
nena suli li pana e ko seli :: Vulkaneruption 
Netelan :: Niederlande, Niederländisch 
ni :: adjektivisches Demonstrativpronomen: dies, diese, dieser, dieses (hier), (das) dort, jenes 
Nijon :: Japan, Japanisch 
ni li ' ike, tawa mi :: Das ist schlecht für mich. / Ich mag es nicht. 
ni li ' jan ala ' jan? :: Ist das ein Mensch? 
ni li jan lili ona nanpa tu. :: Dies ist ihr zweites Kind. 
ni li ' jan seme? :: Wer ist das? 
ni li ' kili ala ' kili? :: Ist das eine Banane? 
ni li ' kule seme? :: Was ist dies für eine Farbe? 
ni li lon kama. :: Es existiert in der Zukunft. 
ni li ' mije monsuta. :: Dies ist ein ängstlicher Mann. 
ni li moku pi tenpo pini. :: Das ist altes Essen. 
ni li ' # mute mute tu. :: Die Antwort ist 42. 
ni li pimeja ala pimeja e suno? :: Verdunkelt dies die Sonne? 
ni li pona. :: Dies ist gut. 
ni li ' pona, tawa mi. :: Das ist gut für mich. / Ich mag das. 
ni li pona tawa mi. :: Ich mag das. 
ni li ' seli lili, tawa mi. :: Dies fühlt sich lauwarm an. 
ni li ' soweli anu seme? :: Ist dies ein Säugetier? 
ni li suwi ala suwi? :: Versüsst es? 
ni li tawa jan pona mi. :: Dies ist für meinen Freund. 
ni li tomo. mi pana e ni tawa sina. :: Dies ist ein Haus. Ich gebe es dir. 
ni li tomo pi jan seme? :: Wessen Haus ist das? 
ni li ' tomo pi telo nasa ala ' tomo pi telo nasa? :: Ist das eine Kneipe? 
ni li ' wan anu seme? :: Ist dies ein Teil? 
nimi (e ) :: Verb, transitiv: bennenen, Namen geben 
nimi pi mi mute :: unsere Namen 
nimi :: Substantiv: Wort, Name 
Nise :: Niger 
ni :: substantivisches Demonstrativpronomen: dies, diese, dieser, dieses (hier), (das) dort, jenes 
noka :: Adjektiv: Fuß-, niedriger, unten 
noka :: adverb: zu Fuß 
noka :: Fuß, Bein 
noka :: Substantiv: Bein, Fuß 
Nosiki :: Norwegen, Norwegisch 
Nusilan :: Neuseeland 
o awen! :: Warte! 
o esun ala e ilo moli! :: Handle nicht mit Waffen! 
o! :: Interjektion: Hallo! (um jemandes Aufmerksamkeit zu erwirken) 
o, :: Interjektion: Leute ansprechen 
o kalama ala! :: Sei still! 
oko :: Adjektiv: optisch, Augen- 
oko :: Auge 
oko mi li lukin pona :: Meine Augen sehen gut. 
oko sina li pona lukin :: Deine Augen sind schön. 
oko :: Substantiv: Auge 
olin :: Adjektiv: Liebes- 
olin (e ) :: Verb, transitiv: (eine Person) lieben 
olin :: (jemanden) lieben 
olin sina li ' pona, tawa mi. :: Deine Liebe tut mir gut. 
olin :: Substantiv: Liebe 
olin suli li ' awen. :: Alte Liebe rostet nicht. 
o lukin e ni! :: Schau das an! 
o lukin e pipi loje ni. :: Siehe diesen roten Käfer. 
o moli e pipi, kepeken palisa. :: Töte den Skorpion mit dem Stock. 
ona anu jan ante li ' ike? :: Ist er oder die andere Person böse? 
ona li anpa e moli. :: Sie besiegte den Tod. 
(ona) li ike :: er/sie/es ist schlecht, Ich mag ihn/sie/es nicht 
ona li ' jan pi pona lukin ala ' jan pi pona lukin? :: Ist sie eine attraktive Persion? 
ona li ' jan pona pi kalama musi. :: Er ist ein guter Musiker. 
ona li jo e seme? :: Was hat er? 
ona li kama, tawa ma mi. :: Er kommt in mein Land. 
ona li kama, tawa tomo mi. :: Er kam zu meinem Haus. 
ona li kasi ala kasi? :: Wächst es? 
ona li kule ala kule e len? :: Färbt sie das Kleid? 
ona li kule e tomo tawa. :: Er lakiert das Auto. 
ona li lawa e jan, tawa ma pona. :: Er führte die Leute in das gelobte Land. 
 :: ona li lawa utala e utala. 
ona li ' linja anu seme? :: Ist es eine Kette? 
ona li ' loje anu seme? :: Ist es rot? 
ona li ' lon ala. :: Es hat keine Existenz. 
ona li lon ala lon tomo? :: Ist er im Haus? 
ona li ' lon pi nasin sewi. :: Es ist eine heilige Existenz. 
ona li lon sewi mi. :: Er ist in dem Bereich über mir. 
ona li lon tenpo ni li lon tomo ni. :: Er ist in dieser Zeit hier und in diesem Haus. 
ona li lukin, sama pipi. :: Er guckt wie ein Käfer. 
ona li mama ala mama e sina? :: Bemuttert sie dich? 
ona li ' mama ala ' mama ? :: Ist sie eine Mutter? 
ona li ' mama anu seme? :: Ist sie eine Mutter (oder was)? 
ona li moku e kili. :: Sie isst Früchte. 
ona li ' moku. :: Es ist Essen. 
ona li moku, lon tenpo ni li moku, lon tenpo kama. :: Er ißt jetzt und er ißt später. 
ona li namako ala namako? :: Hat sie gewürzt? 
ona li nanpa e jan. :: Er zählt die Menschen. 
ona li pali e ni, kepeken nasin seme? :: Wie hat sie das gemacht? 
ona li pali, lon tomo pali li moku, lon tomo moku. :: Er arbeitet im Büro und ißt in der Mensa. 
ona li pan ala pan? :: Sät er? 
ona li pan e pan. :: Sie säen das Getreide. 
ona li pona e ilo, lon tomo ona. :: Er repariert das Werkzeug in seinem Haus. 
ona li pona e ilo. :: Sie repariert die Maschine. 
(ona) li pona :: er/sie/es ist gut, Ich mag ihn/sie/es 
ona li pona ike mute e ilo. :: Er reparierte sehr schlecht die Maschine. 
ona li ' pona li ' lili. :: Sie sind gut und klein. 
ona li ' pona li unpa. :: Er ist toll und hat Sex. 
ona li selo ala selo? :: Schützt es? 
ona li seme? :: Wie ist er/sie so? 
ona li sike ala sike? :: Dreht es (sich)? 
ona li sitelen ala sitelen? :: Zeichnet er? 
ona li tawa ala, tawa telo. :: Er ging nicht zum See. 
ona li tawa, tawa sewi kiwen. :: Sie besteigt die Felsspitze. 
ona li telo e ona. :: Er wäscht sich. 
ona li telo e ona. :: Sie wäscht sich. 
ona li toki sitelen e ni. :: Sie sagt dies sehr bildlich. 
ona li wile e ni: jan li pakala ala e ma e telo e kon. :: Sie wollen nicht, dass Menschen die Umwelt zerstören. 
ona li wile jo e ilo. :: Er will das Werkzeug haben. 
ona li wile mute e ni. :: Sie will viel von diesem. 
ona mute li nasa e jan suli. :: Sie nerven die Eltern. 
ona mute li tawa, tawa utala. :: Sie ziehen in den Krieg. 
ona mute li utala toki. :: Sie streiten. 
ona mute :: sie (3. Person Plural), ihnen 
ona :: Personalpronomen: er, sie, es, sie (Plural) 
ona :: Possessivpronomen: seins, ihres, seine, deren 
Ontula :: Honduras 
o olin e jan poka. :: Liebe deinen Nächsten. 
o open e lupa. :: Öffne die Tür! 
o pali! :: Arbeite! 
o pana e namako, tawa mi. :: Gib mir bitte Gewürze. 
o pana e pona tawa ma. :: Gib der Erde nur Gutes. 
o pana e sike, tawa mi. :: Gib mir den Ball. 
o pana e sitelen ma, tawa mi. :: Gib mir die Landkarte. 
o pana e suwi, tawa mi! :: Gib mir einen Lutscher! 
open :: Adjektiv: (er-)öffnend 
open (e ) :: Verb, transitiv: öffnen, andrehen, anmachen, anschalten, beginnen, anfangen 
open :: Hilfsverb: beginnen, starten 
open la ala li lon! :: Am Anfang war nichts! 
open la :: Substantiv: zu Anfang, bei Beginn, beim Start 
open :: Substantiv: Anfang, Beginn, Start 
o pilin e nena. :: Drücke den Knopf. 
o pilin e uta mi, kepeken uta sina. :: Küss mich. 
o ' pona! :: Sei brav! 
o pu! :: Kaufe und lies das offiziellen Toki Pona Buch! 
Osalasi :: Österreich 
Oselija :: Australien 
o ! :: Separator: Ein o wird bei Befehlen verwendet und ersetzt li . 
o sona e sina! :: Lerne dich kennen! 
o ! :: Subjekt: Ein o wird bei Befehlen verwendet und ersetzt das Subjekt. 
o tawa! :: Geh! 
o tawa musi, lon poka mi! :: Tanze mit mir! 
o tawa, tawa ma tomo, lon poka jan pona sina! :: Gehe mit deinem Freund in die Stadt. 
o tawa weka ala e sina! :: Bewege dich nicht weg! 
o tu e palisa ni. :: Zerbrich diesen Stock. 
o tu. :: Teile. Zerbrich. 
o wan! :: Vereinigt euch! 
o weka e jan lili, tan ni. :: Bring das Kind weg von hier. 
o weka e len sina. :: Zieh dich aus. 
pakala :: Adjektiv: ruiniert, zerstört, zerbrochen 
pakala :: Adverb: ruiniert, zerstört, zerbrochen 
pakala (e ) :: Verb, transitiv: verpfuschen, zerstören, ruinieren, verletzen 
pakala! :: Interjektion: Verdammt! 
pakala moli li kama, tawa sina. :: Die tödliche Schlacht kommt zu euch. 
pakala! :: Scheiße! 
pakala! :: Scheiße! (alle derben Flüche) 
pakala :: Substantiv: Fehler, Unfall, Havarie, Error, Vernichtung, Zerstörung, Schaden 
pakala :: Verb, intransitiv: vermasseln, auseinander fallen, brechen, 
Pakisan :: Pakistan 
Palakawi :: Paraguay 
Palani :: Bahrein 
Palata :: Indien 
pali :: Adjektiv: aktiv, tätig, Arbeits-, arbeitend, berufstätig, werktätig 
pali :: Adverb: aktiv, tätig, arbeitend, berufstätig, werktätig 
pali ala :: arbeitslos, nicht arbeitend 
pali :: Arbeit 
pali :: Beruf, Beschäftigung 
pali e ike tawa :: jemandem etwas Schlechtes antun, jemand geringschätzen 
pali (e ) :: Verb, transitiv: tun, machen, bauen, erstellen 
pali li pana e sona. :: Tun bringt Wissen. 
pali pona li lawa, tawa lon. :: Ordnung ist das halbe Leben. 
palisa :: Adjektiv: lang, länglich 
palisa (e ) :: Verb, transitiv: strecken, sexuell erregen 
palisa lili noka :: Zehen 
palisa luka :: Finger 
palisa mije li lawa e mije. :: Der Penis steuert den Mann. 
palisa mije :: Penis 
palisa :: Substantiv: Rute, Stab, Stange, Angel, Stock, Stiel, Ast, Stock 
palisa tawa :: Vibrator 
palisa uta :: Zunge 
pali :: Substantiv: Tätigkeit, Betätigung, Arbeit, Tat, Projekt 
pali :: Verb, intransitiv: handeln, arbeiten, funktionieren 
pana :: Adjektiv: großzügig 
pana e ko jaki :: ein Würstchen machen, Aa machen, käckern, scheißen 
pana e moku tawa :: füttern, ernähren 
pana e palisa lon lupa :: eindringen 
pana e pilin pona tawa :: zu jemandem gut sein, jemandem Freude bereiten 
pana e sona :: lehren, unterrichten, Wissen geben 
pana e telo jelo :: pullern, pinkeln, urinieren 
pana e telo oko :: weinen, beweinen, heulen, flennen 
pana e telo (walo) mije :: ejakulieren 
pana e uta lon lupa (meli) :: Cunnilingus 
pana (e ) :: Verb, transitiv: geben, senden, entbinden, strahlen, emittieren 
Panama :: Panama 
pana :: Substantiv: Verabreichung, Transformation, Überführung, Umtausch 
pan (e ) :: Verb, transitiv: säen, aussäen 
Panla :: Bangladesch, Bengali 
pan ni li ' ike. :: Diese Pasta schmeckt nicht. 
pan :: Substantiv: Getreide, Körner; Gerste, Mais, Hafer, Reis, Weizen, Brot, Nudeln 
Papeto :: Barbados 
Papuwanijukini :: Papua-Neuguinea 
Pasila :: Brasilien 
Pawama :: Bahamas 
Pelalusi :: Weißrussland, Belarussisch
Pelu :: Peru 
Pemuta :: Bermuda 
Penesuwela :: Venezuela 
Penin :: Benin 
Pesije :: Belgien 
pilin :: Adjektiv: sensitiv, fühlend, empathisch 
pilin :: Adverb: einfühlsam 
pilin ala :: abgestumpft, gleichgültig, teilnahmslos, gefühllos 
pilin e ike jan :: jemanden bemitleiden 
pilin e moli jan :: um jemanden trauern 
pilin (e ) :: Verb, transitiv: denken, wahrnehmen, berühren, anfassen 
pilin e weka jan :: jemanden vermissen 
pilin :: fühlen, denken, Gefühl, Herz 
pilin :: Gefühle, Gedanken 
pilin :: Gefühl, Emotion, Ergriffenheit, fühlen, Herz 
pilin :: Herz 
pilin ike tan :: Angst haben vor, traurig sein wegen, bereuen, beleidigen 
pilin ike tawa :: negative Gefühle für ..., wütend auf ..., hassen, verübeln 
pilin ike :: traurig, bedrückt, deprimiert, niedergeschlagen, missmutig 
pilin ike wawa :: starke negative Gefühle, richtig abkotzen, grimmig, wütend 
pilin nasa :: albern fühlen, fremdeln, verrückt fühlen, betrunken sein 
pilin nasa :: betrunken, berauscht 
pilin pona :: gut drauf sein, fröhlich sein, selbstzufrieden 
pilin pona li pana e sijelo pona. :: Gute Gedanken heilen. 
pilin pona mute :: sich großartig fühlen, himmelhoch jauchzend, supergeil 
pilin pona tan :: froh sein wegen ... 
pilin :: Substantiv: Gefühl, Emotion, Herz 
pilin :: Verb, intransitiv: fühlen, spüren, verspüren, empfinden 
pilin wawa :: sich stark fühlen, aufgeregt sein, selbstsicher sein, stolz 
pilin wawa (unpa) :: Orgasmus 
Pilipina :: Philipinen, Tagalog 
Pilisin :: Palästina 
pimeja :: Adjektiv: schwarz, dunkel 
pimeja (e ) :: Verb, transitiv: verdunkeln, schwärzen 
pimeja laso :: bläuliches Schwarz 
pimeja :: schwarz, dunkel 
pimeja :: Substantiv: Dunkelheit, Finsternis, Schwärze, Schatten 
pini :: Adjektiv: abgeschlossen, vollendet, beendet, erledigt, fertiggestellt 
pini :: Adverb: vor, vorbei, vorüber, perfekt, vollendet 
pini (e ) :: Verb, transitiv: beenden, erledigen, fertigstellen, vollenden 
pini :: Hilfsverb: stoppen, beenden, unterbrechen 
pini li ' pona la ale li ' pona. :: Ende gut - Alles gut. 
pini palisa :: Glans, Eichel 
pini pi nena mama :: Brustwarzen 
pini :: Substantiv: Ende, Zweck, Ziel, Tip 
pipi li ' ike, tawa mi. :: Ich hasse Spinnen. 
pipi li lon ala lon poka mi? :: Ist ein Käfer neben mir? 
pipi li lon anpa mi. :: Der Käfer ist an meiner Unterseite. 
pipi li moku ala moku e kili? :: Fressen Käfer Früchte? 
pipi li moku e kasi. :: Käfer fressen Pflanzen. 
pipi li moku e mi. :: Ein Moskito hat mich gestochen. 
pipi li mu e kalama. :: Die Zikaden zirpen Geräusche. 
pipi li mu, tawa ona. :: Die Käfer kommunizieren untereinander. 
pipi pi ma mama mi li ' lili. :: Die Käfer meines Heimatlandes sind klein. 
pipi seme li pakala e sina? :: Welches Insekt hat dir weh getan? 
pipi :: Substantiv: Insekt, Käfer, Spinne, Skorpion, Krebs, Krabbe, Schmetterling, Ameise 
pi :: Separator: pi ermöglicht komplexe Substantive. Es trennt ein Substantiv von einem anderen Substantiv, das mindestens ein Adjektiv hat. Nach pi kann nur ein Substantiv oder Pronomen folgen. 
Pisi :: Fidschi 
Piten :: Großbritannien 
poka :: Adjektiv: angrenzend, benachbart 
poka :: Hüfte 
poka mi li ' pakala. :: Meine Hüften schmerzen. 
poka pi luka sitelen ala :: linke Seite, Links 
poka pi luka sitelen :: rechte Seite, Rechts 
Pokasi :: Bulgarien, Bulgarisch 
poka sina la mi tawa. :: Ich gehe an deiner Seite. 
poka :: Substantiv: Seite, Hüfte, Nähe 
poka telo :: Strand, Ufer 
poki (e ) :: Verb, transitiv: einpacken, einwecken, einwickeln, einmachen 
poki :: Glas, Tasse, Flasche, Schüssel, Schale, Napf, Behälter, Gefäß 
poki kon :: Lungen 
poki lete :: Kühlschrank 
poki lete :: Kühlschrank, Eisschrank, Tiefkühltruhe 
poki ni li lon jaki. :: Diese Flasche ist im Dreck. 
poki seli :: Ofen, Mikrowelle 
poki :: Substantiv: Container, Behälter, Box, Schüssel, Schale, Tasse, (Trink-) Glas 
poki telo :: Spüle, Spülbecken, Badewanne, Waschbecken 
pona :: Adjektiv: gut, einfach, positiv, schön, richtig, korrekt, toll 
pona :: Adverb: gut, einfach, schön, richtig, korrekt, toll 
pona e pilin jan :: jemanden aufheitern, jemanden glücklich machen 
pona (e ) :: Verb, transitiv: verbessern, fixen, reparieren, festmachen 
pona! :: Interjektion: Toll! Gut! Danke! OK! Cool! Fantastisch! 
pona! :: Juhu! Toll! Hurra! Cool! 
pona la sina jo e mani. :: Glücklicherweise hast du Geld. 
pona la :: Substantiv: zum Glück, einfacherweise 
pona li kama ala kama? :: Kommt das Gute? 
pona li kama. :: Das Gute wird kommen. 
pona lukin :: schön, hübsch, adrett, fesch, schick, reizend, nett 
pona lukin :: schön, hübsch, attraktiv 
pona moku :: appetitlich, köstlich, wohlschmeckend, schmackhaft 
pona :: Substantiv: das Gute, Einfachheit, Positivismus 
pona unpa :: sexy, guten Sex haben 
Posan :: Bosnien-Herzegowina, Bosnisch 
Posuka :: Polen, Polnisch 
Potuke :: Portugal, Portugiesisch 
pu :: Adjektiv: Kaufen und Lesen des offiziellen Toki Pona Buchs 
pu (e ) :: Verb, transitiv: anwenden der Regeln des offiziellen Toki Pona Buches 
pu (e ) :: Verb, transitiv: Anwenden der Regeln des offiziellen Toki Pona Buches 
pu :: Hilfsverb: Kaufen und lesen des offiziellen Toki Pona Buchs 
pu :: Hilfsverb: Kaufen und Lesen des offiziellen Toki Pona Buchs 
pu :: Substantiv: Einkauf und Lesung des offiziellen Toki Pona Buchs 
pu :: Verb, intransitiv: Kaufen und Lesen des offiziellen Toki Pona Buch 
sama :: Adjektiv: gleichaltrig, ähnlich, paritätisch 
sama :: Adverb: ähnlich 
sama (e ) :: Verb, transitiv: gleichsetzen, gleich machen, nachäffen 
sama la sina en mi li utala ala. :: Bei Parität kämpfen wir nicht. 
sama la :: Substantiv: bei Gleichheit, bei Parität, bei Identität 
sama li ' ike. :: Gleichheit ist schlecht. 
Samalino :: San Marino 
sama ona la sina ken ante e ni. :: Bei Gleichheit kannst du dies vertauschen. 
sama pi ni en ona la mi wile jo e ni tu. :: Wenn dieses und jenes gleich ist, will ich beides. 
sama :: Präposition: wie, dergleichen 
sama :: Substantiv: Gleichheit, Parität, Identität 
Sameka :: Jamaika, Jamaikisch 
Samowa :: Samoa 
Sasali :: Algerien 
Sawa :: Java, Javanesisch 
Sawasi :: Swasiland 
Seki :: Tschechische Republik, Tschechisch 
seli :: Adjektiv: heiß, warm, gar 
seli :: Adverb: heiß, warm 
seli (e ) :: Verb, transitiv: erhitzen, erwärmen, aufwärmen, kochen 
seli lili li lon. :: Es ist lauwarm. 
seli li lon. :: Es ist heiß. 
seli li lon :: es ist warm/heiß 
seli li lon la mi pana e telo, tan selo mi. :: Wenn es warm ist, schwitze ich. 
seli mute li lon. :: Es ist sehr heiß. 
seli :: Substantiv: Feuer, Wärme, Hitze 
seli suno li seli e tomo mi. :: Die Sonnenhitze wärmt mein Haus. 
selo (e ) :: Verb, transitiv: schützen, bewachen 
selo :: Haut 
selo lon pini palisa :: Vorhaut, Präputium 
selo mi li wile e ni: mi pilin e ona. :: Meine Haut juckt. 
selo pi jelo en laso pi akesi lili li ' pona, tawa mi. :: Die grün-blau gescheckte Haut der kleinen Echse gefällt mir. 
selo :: Substantiv: Außenseite, Oberfläche, Haut, Schale, Rinde, Borke, Gestalt, Form 
seme :: Fragepronomen: wer, wie, was, welche, warum, wessen (Fragewort) 
seme la sina pali e ni? :: Unter welchen Bedingungen werden Sie das tun? 
seme la telo kama, tan sewi? :: Unter welchen Bedingungen regnet es? 
seme li lon poka mi? :: Wer/Was ist neben mir? 
seme li lon tomo mi? :: Wer/Was ist in meinem Haus? 
seme li moku e kili mi? :: Wer/Was aß meine Frucht? 
seme li ' pona, tawa sina? :: Was magst du? 
seme li utala e sina? :: Wer/Was hat dich geschlagen? 
seme? :: Wie bitte? 
Seneka :: Senegal 
" :: Separator: Anführungszeichen werden für Zitate oder Originalschreibweise verwendet. 
! :: Separator: Aufforderungssätze (Imperativ) und Ausrufesätze (Interjektionen, Exclamatory) enden mit einem Ausrufungszeichen. Verwende ein Ausrufungszeichen nicht zusammmen mit einem der anderen Separatoren. 
. :: Separator: Beendet wird ein Aussagesatz ((Deklarativsatz)) mit einem Punkt. Verwende einen Punkt nicht zusammmen mit einem der anderen Separatoren. 
? :: Separator: Beendet wird eine Frage (Interrogativ) mit einem Fragezeichen. Verwende ein Fragezeichen nicht zusammmen mit einem der anderen Separatoren. 
: :: Separator: Ein Doppelpunkt trennt ein Hinweis-Satz von einem Satz. Jeweils vor und nach dem Doppelpunkt muss ein vollständiger Satz sein. Verwende einen Doppelpunkt nicht zusammmen mit einem der anderen Separatoren. 
, :: Separator: Ein Komma wird nach o verwendet, wenn man Leute anspricht. Optional kann es vor einer Präposition eingefügt werden. Verwende ein Komma nicht zusammmen mit einem der anderen Separatoren ausser li. 
Setapika :: Südafrika 
sewi :: Adjektiv: übergeordnet, oberer, erhöht, erhaben, religiös, gläubig, formell 
sewi :: Adverb: übergeordnet, erhöht, erhaben, gläubig, formell 
sewi (e ) :: Verb, transitiv: heben, anheben 
sewi li ' laso. :: Der Himmel ist blau. 
sewi monsi :: Achseln, Schultern 
sewi pi sinpin lawa :: Stirn 
sewi :: Substantiv: Höhe, Himmel, Dach, Gipfel, Spitze, Krone 
sewi :: Verb, intransitiv: aufstehen 
Sie hat Durst. :: ona li wile moku e telo. 
Sie ist gut. :: ona li ' pona. 
Sie kleidete sich wenig. :: ona li len lili e ona. 
Sie vermehrt sehr schlecht den Besitz. :: ona li mute ike mute e jo. 
sijelo :: Adjektiv: körperlich, materiell, fleischlich 
sijelo :: Adverb: körperlich 
sijelo (e ) :: Verb, transitiv: heilen 
sijelo :: Gesundheit 
sijelo :: Körper 
sijelo :: Substantiv: Körper, Leib, Gesundheit, physischer Zustand 
sike :: Adjektiv: rund, konjunkturell, periodisch 
sike :: Adverb: gedreht 
sike (e ) :: Verb, transitiv: kreisen, drehen 
sike mama waso :: Ei, Eier 
sike mije :: Hoden 
sike mije (tu) :: Hoden 
sike :: Substantiv: Kreis, Rad, Kugel, Ball, Kreislauf, Periode, Zyklus 
sike tu :: Fahrrad 
Sile :: Chile 
sin :: Adjektiv: neu, frisch, noch einer, ein anderes, mehr 
 sin :: Adverb: erneuernd 
sina en mi li ' jan pona. :: Du und ich sind Freunde. 
sina jo e kili anu telo nasa? :: Hast du die Frucht oder den Wein? 
sina kama e ni: mi wile moku. :: Du hast Folgendes bewirkt: Ich habe Hunger. 
sina kama jo e jan pona, lon ni. :: Du bekommst Freunde dort. 
sina kama, tan ma seme? :: Aus welchem Land kommst du? 
sina kama, tan seme? :: Warum kamst du? 
sina ken ala ken kama? :: Kannst du kommen? 
sina ken ala ken lape? :: Kannst du schlafen? 
sina kepeken ala kepeken ilo? :: Verwendest du das Werkzeug? 
sina kepeken ala kepeken ni? :: Hast du dies hier verwendet? 
sina kepeken seme? :: Was nutzt du? 
 :: sina len nasa jaki e sina. 
sina lon ala lon ma tomo Pelin? :: Lebst du in Berlin? 
sina lon ma tomo seme? :: In welcher Stadt wohnst du? 
sina lon seme? :: Wo bist du? 
sina lukin ala lukin e kiwen? :: Siehst du den Felsen? 
sina lukin ala lukin e sitelen tawa X-Files? :: Schaust du dir 'Akte-X' an? 
sina lukin e jan seme? :: Wen hast du gesehen? 
sina lukin e pipi. :: Du schaust dir einen Käfer an. 
sina lukin e seme? :: Was schaust du dir an? 
sina lukin sewi e suno. :: Du schaust zur Sonne hoch. 
 :: sina lukin unpa mute e mi. 
sina moku e telo nasa la sina ' nasa. :: Wenn du Bier trinkst, bist du albern. 
sina ' moli la sina ken ala toki. :: Wenn du tot bist, dann kannst du nicht sprechen. 
sina o telo e sina! :: Wasch dich! 
sina pakala e ilo, kepeken nasin seme? :: Wie hast du das Werkzeug zerbrochen? 
sina pakala e seme? :: Was hast du beschädigt? 
sina pali e ni, kepeken nasin seme? :: Wie hast du das gemacht? 
sina pali e ni, kepeken seme? :: Was hast du verwendet, um dies zu bearbeiten? 
sina pana ala pana e moku tawa jan lili? :: Hast du dem Kind zu Essen gegeben? 
sina pana e ike la sina kama jo e ike. :: Wenn du Böses säst, wirst du Böses ernten. 
sina :: Personalpronomen: du, ihr (Plural) 
sina pilin e seme? :: Was denkst du? 
sina pilin pona anu seme? :: Geht es dir gut? 
sina pilin seme? :: Wie fühlst du dich? 
sina pilin seme? :: Wie geht es dir? Wie fühlst du dich? 
sina pona ala pona? :: Bist du OK? 
sina pona ala pona e ilo? :: Reparierst du das Werkzeug? 
sina pona ala pona e sina? sina pona e sina anu seme? :: Hast du dich verbessert? 
sina ' pona ala ' pona? :: Geht es dir gut? 
sina ' pona anu seme? :: Bist du OK (oder was)? 
sina ' pona. :: Du bist gut. 
sina pona. :: Du reparierst. 
sina pona pilin la ... :: Wenn du glücklich bist ... 
sina :: Possessivpronomen: deins, euer 
sina sewi ala sewi? :: Stehst du auf? 
sina sona ala sona e toki mi? :: Hast du verstanden was ich sagte? 
sina sona e toki ni la sina sona e toki pona! :: Finde dies selber raus :o) 
sina ' suli a! :: Du bist so groß. 
sina ' suli. :: Du bist groß. 
sina suno mi. :: You are My Sunshine. 
sina tawa ala tawa, tan mi? :: Verlässt du mich? 
sina tawa, lon poka pi jan seme? :: Mit wem bist du gegangen? 
sina tawa ma tomo, tan seme? :: Warum gingst du in die Stadt? 
sina tawa, tan mi. :: Du verlässt mich. 
sina telo e sina. :: Du wäschst dich. 
sina toki e ni, tawa mi: sina moku. :: Du sagtest zu mir, dass Du isst. 
sina toki mu e ni. :: Du sprichst dies tierisch aus. 
sina toki, tawa jan seme? :: Mit wem redest du? 
sina toki, tawa mi anu ona? :: Sprichst du zu mir oder zu ihm? 
sina wile ala wile moku? :: Möchtest du essen? 
sina wile ala wile pali? wile ala. :: Willst du arbeiten? Nein. 
sina wile e moku anu telo? :: Willst du das Essen oder das Wasser? 
sina wile jo e ilo moli la sina wile moli e jan. :: Wenn du eine Waffe möchtest, willst du Menschen töten. 
sina wile kama anu seme? :: Möchtest du kommen oder was? 
sina wile kama, tawa tomo toki. :: Du solltest in den Chat-Room kommen. 
sina wile kepeken ilo. :: Du mußt die Hilfsmittel verwenden. 
sina wile pali e seme? :: Was möchtest du tun? 
sina wile tawa, tawa ma seme? :: In welches Land willst du gehen? 
sina wile tawa, tawa telo suli. :: Du willst zum Meer gehen. 
sina wile toki e tan, tawa mi. :: Du mußt mir sagen warum! 
sina wile toki, tawa mije anu meli? :: Möchtest du zu einem Mann oder einer Frau sprechen? 
sin (e ) :: Verb, transitiv: erneuern, renovieren, auffrischen, beleben 
Sinita :: Trinidad und Tobago 
sinpin :: Adjektiv: Gesichts-, frontal, Vorder-, vertikal 
sinpin :: Brust, Brustkorb, Brustkasten, Unterleib, Bauch, Gesicht 
sinpin (lawa) :: Gesicht 
sinpin mi la tomo li lon. :: Vor mir befindet sich das Haus. 
sinpin :: Substantiv: Front, Vorderseite, Gesicht, Brust, Brustkorb, Rumpf, Wand, Mauer 
sin :: Substantiv: Nachrichten, Neuheit, Innovation 
Sipusi :: Dschibuti 
sitelen :: Adjektiv: bildlich, figurativ, bildhaft, metaphorisch 
sitelen :: Adverb: bildlich 
sitelen e toki :: schreiben 
sitelen (e ) :: Verb, transitiv: zeichnen, malen, schreiben 
sitelen lape :: Traum 
sitelen ma :: Landkarte 
sitelen :: Substantiv: Bild, Abbildung, Foto, Film, Darstellung, Gemälde 
sitelen tawa 'Bowling for Columbine' li pona kin. :: Der Film 'Bowling for Columbine' ist auch gut. 
sitelen tawa 'Fahrenheit 9/11' li pona, tawa mi. :: Ich mag den Film 'Fahrenheit 9/11'. 
sitelen tawa :: Film (bewegte Bilder) 
sitelen toki :: vorlesend 
sitelen unpa :: Aktfoto, Porno 
sona :: Adjektiv: wissend, verständnisvoll, klug, schlau, clever 
sona e toki :: eine Sprache verstehen 
sona (e ) :: Verb, transitiv: wissen, können, verstehen, zu etwas fähig sein 
sona :: Hilfsverb: wissen 
sona mute :: intelligent, klug, weise, wissend 
sona pona e toki :: eine Sprache meistern 
sona :: Substantiv: Kenntnis, Wissen, Erkenntnis, Weisheit, Intelligenz, Verständnis 
sona :: Verb, intransitiv: wissen, können, verstehen 
sona :: Weisheiten 
Sonko :: China, Chinesisch 
Sopisi :: Serbien, Serbisch 
soweli :: Adjektiv: tierisch 
soweli li kama ala kama moli? :: Stirbt der Hund? 
soweli li kama moli. :: Der Hund stirbt. 
soweli lili li ' ike, tawa mi. :: Ich habe eine Katzenallergie. 
soweli li toki e mu. :: Kühe sagen Muuh. 
soweli mi li kama moli. :: Mein Hund stirbt. 
soweli ni li ' pona moku. :: Das Kalbfleisch schmeckt gut. 
soweli pi poki sinpin :: Kaenguru 
soweli :: Substantiv: (Land-) Säugetier, Hund, Kuh, Maus, Elefant, Katze, Fleisch 
soweli :: Säugetierfleisch, Beef, Schweinefleisch, Eisbein 
soweli waso :: Fledermaus 
Sukosi :: Schottland 
suli :: Adjektiv: groß, schwer, wichtig, lang, erwachsen 
suli :: Adverb: schwer, wichtig, erwachsen 
suli (e ) :: Verb, transitiv: vergrößern, ausbauen, ausdehnen, verlängern 
suli :: groß, lang, hoch, dick, fett 
Sulija :: Syrien 
suli :: Substantiv: Größe, Format 
Sumi :: Finnland, Finnisch 
suno :: Adjektiv: sonnig 
suno :: Adverb: sonnig 
suno (e ) :: Verb, transitiv: scheinen, beleuchten 
suno li ' jelo. :: Die Sonne ist gelb. 
suno li lon :: es ist sonnig 
suno li lon poka pimeja. :: Wo Licht ist, ist auch Schatten. 
suno li lon sewi. :: Die Sonne ist am Himmel. 
suno li lon sewi mi. :: Die Sonne ist über mir. 
suno li ' suli ala ' suli? :: Ist die Sonne groß? 
suno li ' suli. :: Die Sonne ist groß. 
suno li suno. :: Die Sonne scheint. 
suno pona! :: Guten Tag! 
suno :: Substantiv: Sonne, Licht, Helligkeit 
supa :: Adjektiv: flach, eben, plan, platt, seicht, horizontal 
supa lape :: Bett 
supa lawa :: Kissen 
supa moku :: Eßtisch 
supa monsi :: Stuhl, Sessel, Couch, Sofa 
supa pali :: Arbeitstisch, Schreibtisch, Werkbank 
supa :: Substantiv: horizontale Fläche, Möbel, Tisch, Stuhl, Kissen, Fußboden 
supa :: Tisch, Sessel, Stuhl, Sofa, Liege 
Sutan :: Sudan 
Suwasi :: Schweiz 
suwi :: Adjektiv: süß, niedlich 
suwi (e ) :: Verb, transitiv: süßen, versüßen 
suwi lukin :: hübsch, reizend, niedlich, süß 
suwi :: süß 
suwi :: Substantiv: Süßigkeiten, Zucker, Schokolade, Bonbon 
tan :: Adjektiv: kausal, ursächlich 
tan ni la mi sona e nasin. :: Wenn dies die Ursache ist, wissen wir die Lösung. 
tan :: Präposition: von, aus, durch, wegen, weil, seit 
Tansi :: Dänemark, Dänisch 
tan :: Substantiv: Ursprung, Abstammung, Herkunft, Entstehung, Grund, Ursache 
tan :: Verb, intransitiv: stammen aus, kommen aus 
taso :: Adjektiv: nur, einzig, alleinig 
taso :: Adverb: nur, einzig, alleinig 
taso :: Konjunktion: aber, sondern, doch 
taso ni la mi pilin pona. :: Aber wenn dies eintritt, fühle ich mich gut. 
taso tenpo pimeja pini la mi kama nasa. :: Aber letzte Nacht war ich betrunken. 
tawa :: Adjektiv: beweglich, mobil 
tawa :: Adverb: beweglich, mobil 
tawa (e ) :: Verb, transitiv: bewegen, verschieben, verlagern 
tawa mi la li ' pona, tawa mi. :: Wenn ich in Bewegung bin tut mir das gut. 
tawa mi la mi pilin pona. :: Bin ich in Bewegung, ich fühle mich gut. 
tawa musi :: tanzen 
tawa pona! :: Tschüß!. (Das sagt der, der geht.) 
tawa pona! :: Tschüss! Auf Wiedersehen! (als Antwort) 
tawa :: Präposition: zu, um zu, zu hin, nach, für, bis, in 
tawa :: Substantiv: Bewegung, Regung, Transport 
tawa :: Verb, intransitiv: gehen, spazieren, verlassen, abfahren, reisen, besuchen 
Tawi :: Thailand, Thai 
telo :: Adjektiv: feucht, klebrig, verschwitzt 
telo :: Adverb: feucht, klebrig, verschwitzt 
telo e mi :: duschen 
telo (e ) :: Verb, transitiv: begießen, bewässern, befeuchten, waschen, schmelzen 
telo jaki lon nena sinpin :: Rotz 
telo jelo :: Urin, gelbe Flüssigkeit 
telo jelo :: Urin, Pisse 
telo kili :: Juice, (Frucht-) Saft 
telo kili ni li ' suwi. :: Dieser Saft ist süß. 
telo kiwen :: Eis, Eiswürfel, Eisblock 
telo kiwen lili li kama :: es hagelt 
telo li kama :: es regnet 
telo lili li lon kon :: es ist neblig, feucht 
telo li ' pona. :: Wasser ist einfach. 
telo li ' pona. :: Wasser ist gut. 
telo li pona. :: Wasser reinigt. 
telo li ' suli. :: Der See ist groß. 
telo loje :: Blut 
telo (loje) mun :: Menstruation 
telo mama soweli :: (Kuh-) Milch 
telo nasa :: Alkohol, Bier, Wein, Schnaps 
telo nasa :: Alkohol, z.B. Bier, Wein, Whisky 
telo nasa :: berauschende Flüssigkeit, Alkohol 
telo nasa pi wawa ala :: Dünnbier, us-amerikanisches Bier 
telo nasa wawa :: Wodka, Whisky, Rum, Schnaps, Kumpeltod, Fusel
telo ni li ' lete, tawa mi. :: Dieser See ist kalt. 
telo ona :: sein Wasser 
telo pi lape ala :: Kaffee 
telo seli :: heißes Getränk, Kaffee, Tee 
telo seli jelo :: grüner Tee 
telo seli pimeja pi lape ala :: Kaffee 
telo seli wawa :: Kaffee 
telo sijelo loje :: Blut, rote Körperflüssigkeit 
telo :: Substantiv: Wasser, Flüssigkeit, Feuchtigkeit, Saft, Soße 
telo suli li ' ike, tawa mi. :: Ich mag das Meer nicht. 
telo suli li ' laso. :: Das Meer ist blau. 
telo suli li lon monsi mi. :: Das Meer liegt hinter mir. 
telo (walo) mije :: Sperma 
telo walo mije :: Sperma, Samen 
telo :: Wasser, Getränke, Flüssigkeit, Soße 
telo wawa :: Energy-Drink 
telo wawa :: Energy-Drink, Energie-Getränk 
tenpo :: Adjektiv: zeitlich, chronologisch 
tenpo :: Adverb: chronologisch 
tenpo ala :: niemals 
tenpo ali :: immer, jederzeit 
tenpo ali la o kama sona! :: Lerne immer! 
tenpo kama la mi lape. :: Ich werde schlafen. 
tenpo kama la ona li wile lon kin. :: Sie wollen auch in der Zukunft leben können. 
tenpo kama lili :: bald, einen Moment 
tenpo kama :: Zukunft 
tenpo la mi pali e ni. :: Wenn Zeit ist, mache ich es. 
tenpo lete :: Winter 
tenpo lili :: bald 
tenpo lili :: kurze Zeit, Moment 
tenpo li pona e sijelo ike ale. :: Die Zeit heilt alle Wunden. 
tenpo li tawa la sona li kama. :: Kommt Zeit, kommt Rat. 
tenpo moku :: Essenszeit 
tenpo mute :: oft, mehrmals 
tenpo ni en tenpo kama la ona li moku. :: Jetzt und später ißt er. 
tenpo ni :: jetzt, Gegenwart 
tenpo ni la mi lon. :: Jetzt bin ich hier. 
tenpo ni la mi lon. :: Jetzt existiere ich. 
tenpo ni la mi moku e telo. :: Wenn es jetzt ist, trinke ich. / Ich trinke jetzt. 
tenpo ni la ona li lon tomo ni. :: Zu dieser Zeit ist er im Haus. 
tenpo ni la tenpo kama la ona li moku. :: Jetzt und später ißt er. 
tenpo ni la tomo ni la ona li lon. :: Zu dieser Zeit und in diesem Haus ist er. 
tenpo pi kasi loje (jelo) :: Herbst 
tenpo pimeja kama :: kommende Nacht 
tenpo pimeja mute :: viele Nächte 
tenpo pimeja :: Nacht 
tenpo pimeja ni :: heute Nacht 
tenpo pimeja ni la mun li ' suli anu seme? :: Ist der Mond groß heute Nacht? 
tenpo pimeja pini la mi lukin e sitelen tawa X-Files. :: Letzte Nacht sah ich 'Akte-X'. 
tenpo pimeja pini :: letzte Nacht 
tenpo pimeja sin :: abends 
tenpo pi mute seme la sina sike e suno? :: Wie alt bist du? 
tenpo pini la mi ' weka. :: Ich war weg. 
tenpo pini lili :: gerade erst 
tenpo pini :: Vergangenheit 
tenpo seli lili :: Frühling 
tenpo seli :: Sommer 
tenpo sike mun :: Monat 
tenpo sike mun nanpa luka luka :: Oktober 
tenpo sike mun nanpa luka luka tu :: Dezember 
tenpo sike mun nanpa luka luka wan :: November 
tenpo sike mun nanpa luka :: Mai 
tenpo sike mun nanpa luka tu :: Juli 
tenpo sike mun nanpa luka tu tu :: September 
tenpo sike mun nanpa luka tu wan :: August 
tenpo sike mun nanpa luka wan :: Juni 
tenpo sike mun nanpa tu :: Februar 
tenpo sike mun nanpa tu tu :: April 
tenpo sike mun nanpa tu wan :: März 
tenpo sike mun nanpa wan :: Januar 
tenpo sike suno :: Jahr 
tenpo sin :: wieder 
tenpo :: Substantiv: Zeit, Zeitperiode, Zeitabschnitt, Moment, Dauer, Situation 
tenpo suli :: lange Zeit, Ewigkeit 
tenpo suno kama la mi wile pali. :: Ich muß morgen arbeiten. 
tenpo suno kama :: morgen 
tenpo suno luka tu pi pali en pali ala :: Woche 
tenpo suno mute :: viele Tage 
tenpo suno ni :: heute 
tenpo suno ni la jan lili pi kama sona li tawa ala, tawa tomo pi kama sona. :: Heute gehen die Schüler nicht zur Schule. 
tenpo suno ni la mun li pimeja ala pimeja e suno? :: Gibt es heute eine Sonnenfinsterniss? 
tenpo suno ni li tenpo suno pali nanpa luka. :: Heute ist Freitag. 
tenpo suno pali ala nanpa tu :: Sonntag 
tenpo suno pali ala nanpa wan :: Sonnabend, Samstag 
tenpo suno pali nanpa luka :: Freitag 
tenpo suno pali nanpa tu :: Dienstag 
tenpo suno pali nanpa tu tu :: Donnerstag 
tenpo suno pali nanpa tu wan :: Mittwoch 
tenpo suno pali nanpa wan :: Montag 
tenpo suno pini :: gestern 
tenpo suno sin ale la mi moku e telo seli pimeja :: Jeden Morgen trinke ich Kaffee. 
tenpo suno sin :: am Morgen 
tenpo suno :: Tag 
tenpo telo ala :: Trockenzeit 
tenpo telo :: Regenzeit 
tenpo tu tu la mi sike e suno. :: Ich bin vier Jahre alt. 
toki :: Adjektiv: eloquent, sprachlich, verbal, grammatisch 
toki :: Adverb: eloquent, sprachlich, verbal, grammatisch 
toki Alapi :: Arabisch 
toki Apikan :: Afrikaans 
toki Awasa :: Hausa 
toki Epelanto :: Esperanto 
toki Epelanto li ' pona. :: Esperanto ist einfach. 
toki (e ) :: Verb, transitiv: sagen 
toki Ewantalu :: Ewantal 
toki! :: Hallo! Guten Tag! Moin! 
toki ike lon :: schlecht sprechen, sich beschweren über 
toki ike :: schlecht sprechen, in schlechten Leumund bringen 
toki ike tawa :: jemanden beleidigen, beschimpfen, kränken 
toki Inli :: Englisch 
toki Inli li ' pona. :: Englisch ist gut. 
toki Inli pona :: Basic English 
toki Insi :: Hindi 
toki Intelinka :: Interlingua 
toki! :: Interjektion: Hallo! Hi! 
toki Inu :: Inupiaq, Inuktitut, Eskimo 
toki Ipo :: Igbo 
toki Ito :: Ido 
toki Iwisi :: Hebräisch 
toki Jolupa :: Yoruba 
toki Kalike :: Schottisches Gaelik 
toki Kanse :: Französisch 
toki Kantun :: Kantonesisch 
toki kepeken toki ... :: in einer Sprache sprechen 
toki Kisawili :: Suaheli, Swahili 
toki Kuwenja :: Quenya, Elvish 
toki li ' pona. :: Kommunizieren ist gut. 
toki li ' pona, tawa mi. :: Ich rede gern. / Ich mag Sprachen. 
toki Lolan :: Loglan 
toki Loma :: Latein 
toki Losupan :: Lojban 
toki Lunasimi :: Quechua 
toki Malasi :: Marathi 
toki mi li ' Tosi. :: Meine Muttersprache ist deutsch. 
toki nanpa wan :: Muttersprache 
toki Nosiki sin :: Norwegian Nynorsk 
toki Olapu :: Volapük 
toki Pansapi :: Punjabi 
toki Pasiki :: Fyksian 
toki Pasuto :: Pashto 
toki Pitaha :: Pirahã 
toki pona e toki :: sprachbegabt 
toki pona li ' pona, tawa mi. :: Ich mag toki pona. 
toki pona li ' toki pona. :: toki pona ist eine gute Sprache. 
toki pona lon :: gut sprechen, jemanden loben 
toki pona :: nette Dinge sagen, schmeicheln 
toki pona tawa :: zu jemandem nette Sachen sagen, Komplimente machen 
toki pona :: toki pona 
toki Sami :: Laplander 
toki Sankitu :: Sanskrit 
toki Sinan :: Klingonisch 
toki sitelen :: geschriebene Sprache 
toki sitelen li ' pona, tawa jan ali. :: Geschriebene Sprache (Schrift) ist gut für alle Menschen. 
toki sona :: Aphorismen, Sprichwörter, Weisheiten 
toki :: Sprache 
toki :: Sprachen 
toki :: Substantiv: Sprache, Gespräch, Rede, Ansprache, Kommunikation, Plauderei 
toki Tamasiko :: Berber, Tamazight 
toki Tami :: Tamil 
toki tan toki pi jan Pokakijo :: Das Dekameron von Giovanni Boccaccio. 
toki Teluku :: Telugu 
toki utala pi pimeja soweli :: des Esels Schatten 
toki utala tawa :: mit jemandem streiten, jemanden kritisieren 
toki Utu :: Urdu 
toki :: Verb, intransitiv: reden, sprechen, sich unterhalten, plaudern 
Toko :: Togo 
Tominika :: Dominikanische Republik 
tomo :: Adjektiv: städtebaulich, Stadt-, häuslich 
tomo :: Adverb: häuslich 
tomo (e ) :: Verb, transitiv: bauen, konstruieren 
tomo :: Gebäude 
tomo lape :: Schlafzimmer 
tomo li lon sinpin mi. :: Das Haus befindet sich vor mir. 
tomo mani :: Bank, Sparkasse 
tomo moku :: Essensraum, Küche, Lebensmittelgeschäft, Restaurant 
tomo moku :: Lebensmittelgeschäft, Bioladen, Restaurant 
tomo ni li pakala. :: Dieses Haus fällt auseinander. 
tomo pali :: Arbeitsplatz, Büro, Fabrik 
tomo pi jan Keli en mije ona li ' suli. :: Das Haus von Keli und ihrem Freund ist groß. 
tomo pi jan Lisa :: Lisas Haus, das Haus von Lisa 
tomo pi jelo en loje pi meli Susan en mije jan Ken li ' nasa, tawa mi. :: Susan und Kens gelb-blau gemustertes Haus sieht seltsam aus. 
tomo pi mi mute li ' pakala. :: Unser Haus ist verwüstet. 
tomo pi ona mute :: deren Haus 
tomo pi tawa ala :: Gefängnis, Strafanstalt, Kerker 
tomo pi telo en moku. :: Restaurant, Gaststätte, Kneipe 
tomo pona mi :: mein schönes Haus 
tomo sona :: Schule, Hochschule, Universität 
tomo :: Substantiv: Gebäude, Bauwerk, Haus, Raum, Konstruktion 
tomo tawa akesi li tawa, lon ma li tawa, lon telo. :: Das Amphibienfahrzeug fährt zu Land und zu Wasser. 
tomo tawa :: Auto, PKW, LKW, Bus 
tomo tawa kon :: Flugzeug, Hubschrauber, Ballon, Zeppelin 
tomo tawa mun :: Raumschiff, UFO 
tomo tawa telo :: Boot, Schiff, Floß 
tomo telo :: Badezimmer, Toilette, WC 
tomo telo :: Waschraum, Toilette, Bad 
tomo unpa :: Bordell, Puff 
tomo unpa :: Schlafzimmer, Boudoir 
Tona :: Tonga, Tongan 
Tosi :: Deutschland, Deutsch 
tu :: 2 
tu :: Adjektiv, Ziffer: zwei, 2 
tu (e ) :: Verb, transitiv: verdoppeln, zweiteilen, teilen, zerschneiden 
Tuki :: Türkei, Turkisch 
Tunisi :: Tunesien 
tu pi ona en sina pi kalama musi li ' pona. :: Euer Musik-Duo ist gut. 
tu :: Substantiv: Duo, Paar 
tu tu :: 2 + 2 = 4 
Tuwalu :: Tuvalu 
tu wan :: 2 + 1 = 3 
Ukanta :: Uganda 
Ukawina :: Ukraine, Ukrainisch 
Ulukawi :: Uruguay 
Uman :: Oman 
unpa :: Adjektiv: erotisch, sexuell, sexy 
unpa :: Adverb: erotisch, sexuell 
unpa (e ) :: Verb, transitiv: mit jemandem schlafen, mit jemandem Sex haben 
unpa nasa :: pervers, abartiger Sex 
unpa :: Sex 
unpa :: Substantiv: Geschlecht, Sex, Sexualität 
unpa :: Verb, intransitiv: Sex haben 
uta :: Adjektiv: mündlich, oral 
uta :: Adverb: mündlich, oral 
uta e :: küssen 
uta (e ) :: Verb, transitiv: küssen, saugen 
utala :: Adjektiv: kämpfend 
utala :: Adverb: kämpfend 
utala (e ) :: Verb, transitiv: schlagen, stoßen, überfallen, kämpfen 
utala li ' ike. :: Kriege sind schlecht. 
utala li ' ike, tawa mi. :: Ich mag keinen Krieg. 
utala :: Substantiv: Konflikt, Disharmonie, Kampf, Krieg, Streit, Gewalt 
uta :: Mund 
uta :: Substantiv: Mund, Maul, Schnabel 
Utun :: Jordanien 
walo :: Adjektiv: weiß, hell, bleich 
walo (e ) :: Verb, transitiv: bleichen 
walo pimeja li ' pona, tawa mi. :: Grau ist meine Lieblingsfarbe. 
walo :: Substantiv: Helligkeit, Weiße 
walo uta :: Zähne 
walo :: weiß, hell 
wan :: 1 
wan :: Adjektiv, Ziffer: 1, eins, ein 
wan (e ) :: Verb, transitiv: einigen, vereinigen, zusammenführen 
wan sijelo :: Körperteil 
wan :: Substantiv: Einheit, Element, Partikel, Teil, Abschnitt, Stück 
Wanuwatu :: Vanuatu 
Wasikano :: Vatikan 
waso :: Adjektiv: vogel-, vogelartig 
waso :: Hühnchen, Geflügel 
waso li ken ala lukin la ona li ken kin jo e kili. :: Ein blindes Huhn findet auch mal ein Korn. 
waso li tawa, lon kon. :: Vögel fliegen in der Luft. 
waso soweli li ' pimeja. :: Die Fledermaus ist schwarz. 
waso :: Substantiv: Vogel, Fledermaus, Geflügel 
waso wawa li tawa e ona, lon kon. :: Der Adler bewegt sich durch die Luft. 
wawa :: Adjektiv: energisch, tatkräftig, stark, hitzig, intensiv 
wawa :: Adverb: stark, kraftvoll 
wawa (e ) :: Verb, transitiv: bestärken, verstärken, ermächtigen 
wawa li lon insa. :: Kraft kommt aus dem Innern. 
wawa :: Substantiv: Energie, Stärke, Mumm, Leistung, Kraft 
weka :: Adjektiv: weg, fort, entfernt, abwesend, fehlend, versäumend 
weka e ike jan :: jemandem verzeihen 
weka (e ) :: Verb, transitiv: wegwerfen, entfernen, abtragen, 
weka lili li ' pona, tawa lawa. :: Eine kurze Abgeschiedenheit ist gut für den Sinn. 
weka sina li ' ike, tawa mi. :: Deine Abwesenheit tut mir nicht gut. 
weka :: Substantiv: Abwesenheit (von), Fehlen, Mangel, Absenz 
Wensa :: Schweden, Schwedisch 
 :: Wie bitte? 
Wije :: Vietnam, Vietnamesisch 
wile :: Adjektiv: notwendig, nötig, erforderlich 
wile e pona tawa jan :: jemandem etwas Gutes wünschen 
wile (e ) :: Verb, transitiv: benötigen, brauchen, müssen, wünschen, wollen, sollen 
wile :: Hilfsverb: wollen, wünschen, müssen 
wile ike :: negative Absichten haben, übelwollend 
wile lape :: müde sein, schläfrig, ruhebedürftig 
wile lawa :: dominant sein wollen 
wile moku e telo :: durstig sein 
wile moku :: hungrig sein 
wile moku :: hungrig sein, durstig sein 
wile moli e jan :: gemeingefährlich, mörderisch, jemanden umbringen wollen 
wile moli :: selbstmordgefährdet sein 
wile mute :: flehen, inständig bitten, großer Wille 
wile mute ike :: zu viel wollen, gierig, habgierig, gefräßig 
wile pali e ijo :: sich langweilen, etwas tun wollen 
wile pana e pona (tawa jan) :: hilfsbereit, zuvorkommend, (jemandem) behilflich sein 
wile pi jan ike li pakala e ijo. :: Die Wünsche schlechter Menschen zerstören Dinge. 
wile pona :: gute Absichten haben, wohlgesonnen sein 
wile sona li mute e sona. :: Neugierde bringt Weisheit. 
wile :: Substantiv: Begehren, Wunsch, Verlangen (nach), Lust (auf), Trieb, Zwang 
wile unpa :: geil 
wile unpa :: geil sein, wollüstig sein 
wile :: wollen, begehren, wünschen, hoffen `.split('\n').map(function(w) {
    var english, entry, tokipona;
    [tokipona, english] = w.split('::');
    return entry = {
      tokipona: tokipona.trim(),
      english: english.trim(),
      tokiponaHTML: selectable(tokipona),
      englishHTML: selectable(english)
    };
  });

}).call(this);
